// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/management/v1/rbac.proto

package managementv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/graphene-ci/graphene/pkg/proto/management/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// RbacAPIName is the fully-qualified name of the RbacAPI service.
	RbacAPIName = "graphene.management.v1.RbacAPI"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// RbacAPIIssueTokenProcedure is the fully-qualified name of the RbacAPI's IssueToken RPC.
	RbacAPIIssueTokenProcedure = "/graphene.management.v1.RbacAPI/IssueToken"
	// RbacAPIWhoAmIProcedure is the fully-qualified name of the RbacAPI's WhoAmI RPC.
	RbacAPIWhoAmIProcedure = "/graphene.management.v1.RbacAPI/WhoAmI"
)

// RbacAPIClient is a client for the graphene.management.v1.RbacAPI service.
type RbacAPIClient interface {
	// IssueToken mints a token for a service account. It cannot be a
	// command: a command's payload AND its result both land in the
	// record's history, and a token value must land nowhere. The value
	// is returned exactly once, here; the record keeps only its hash.
	IssueToken(context.Context, *connect.Request[v1.IssueTokenRequest]) (*connect.Response[v1.IssueTokenResponse], error)
	// WhoAmI answers who the caller is and what they may do — a property
	// of the caller, not of any record.
	WhoAmI(context.Context, *connect.Request[v1.WhoAmIRequest]) (*connect.Response[v1.WhoAmIResponse], error)
}

// NewRbacAPIClient constructs a client for the graphene.management.v1.RbacAPI service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewRbacAPIClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) RbacAPIClient {
	baseURL = strings.TrimRight(baseURL, "/")
	rbacAPIMethods := v1.File_proto_management_v1_rbac_proto.Services().ByName("RbacAPI").Methods()
	return &rbacAPIClient{
		issueToken: connect.NewClient[v1.IssueTokenRequest, v1.IssueTokenResponse](
			httpClient,
			baseURL+RbacAPIIssueTokenProcedure,
			connect.WithSchema(rbacAPIMethods.ByName("IssueToken")),
			connect.WithClientOptions(opts...),
		),
		whoAmI: connect.NewClient[v1.WhoAmIRequest, v1.WhoAmIResponse](
			httpClient,
			baseURL+RbacAPIWhoAmIProcedure,
			connect.WithSchema(rbacAPIMethods.ByName("WhoAmI")),
			connect.WithClientOptions(opts...),
		),
	}
}

// rbacAPIClient implements RbacAPIClient.
type rbacAPIClient struct {
	issueToken *connect.Client[v1.IssueTokenRequest, v1.IssueTokenResponse]
	whoAmI     *connect.Client[v1.WhoAmIRequest, v1.WhoAmIResponse]
}

// IssueToken calls graphene.management.v1.RbacAPI.IssueToken.
func (c *rbacAPIClient) IssueToken(ctx context.Context, req *connect.Request[v1.IssueTokenRequest]) (*connect.Response[v1.IssueTokenResponse], error) {
	return c.issueToken.CallUnary(ctx, req)
}

// WhoAmI calls graphene.management.v1.RbacAPI.WhoAmI.
func (c *rbacAPIClient) WhoAmI(ctx context.Context, req *connect.Request[v1.WhoAmIRequest]) (*connect.Response[v1.WhoAmIResponse], error) {
	return c.whoAmI.CallUnary(ctx, req)
}

// RbacAPIHandler is an implementation of the graphene.management.v1.RbacAPI service.
type RbacAPIHandler interface {
	// IssueToken mints a token for a service account. It cannot be a
	// command: a command's payload AND its result both land in the
	// record's history, and a token value must land nowhere. The value
	// is returned exactly once, here; the record keeps only its hash.
	IssueToken(context.Context, *connect.Request[v1.IssueTokenRequest]) (*connect.Response[v1.IssueTokenResponse], error)
	// WhoAmI answers who the caller is and what they may do — a property
	// of the caller, not of any record.
	WhoAmI(context.Context, *connect.Request[v1.WhoAmIRequest]) (*connect.Response[v1.WhoAmIResponse], error)
}

// NewRbacAPIHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewRbacAPIHandler(svc RbacAPIHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	rbacAPIMethods := v1.File_proto_management_v1_rbac_proto.Services().ByName("RbacAPI").Methods()
	rbacAPIIssueTokenHandler := connect.NewUnaryHandler(
		RbacAPIIssueTokenProcedure,
		svc.IssueToken,
		connect.WithSchema(rbacAPIMethods.ByName("IssueToken")),
		connect.WithHandlerOptions(opts...),
	)
	rbacAPIWhoAmIHandler := connect.NewUnaryHandler(
		RbacAPIWhoAmIProcedure,
		svc.WhoAmI,
		connect.WithSchema(rbacAPIMethods.ByName("WhoAmI")),
		connect.WithHandlerOptions(opts...),
	)
	return "/graphene.management.v1.RbacAPI/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case RbacAPIIssueTokenProcedure:
			rbacAPIIssueTokenHandler.ServeHTTP(w, r)
		case RbacAPIWhoAmIProcedure:
			rbacAPIWhoAmIHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedRbacAPIHandler returns CodeUnimplemented from all methods.
type UnimplementedRbacAPIHandler struct{}

func (UnimplementedRbacAPIHandler) IssueToken(context.Context, *connect.Request[v1.IssueTokenRequest]) (*connect.Response[v1.IssueTokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("graphene.management.v1.RbacAPI.IssueToken is not implemented"))
}

func (UnimplementedRbacAPIHandler) WhoAmI(context.Context, *connect.Request[v1.WhoAmIRequest]) (*connect.Response[v1.WhoAmIResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("graphene.management.v1.RbacAPI.WhoAmI is not implemented"))
}
