// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/management/v1/revisions.proto

package managementv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/graphene-ci/graphene/pkg/proto/management/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// RevisionsAPIName is the fully-qualified name of the RevisionsAPI service.
	RevisionsAPIName = "graphene.management.v1.RevisionsAPI"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// RevisionsAPIMaterializeProcedure is the fully-qualified name of the RevisionsAPI's Materialize
	// RPC.
	RevisionsAPIMaterializeProcedure = "/graphene.management.v1.RevisionsAPI/Materialize"
	// RevisionsAPIRunRevisionProcedure is the fully-qualified name of the RevisionsAPI's RunRevision
	// RPC.
	RevisionsAPIRunRevisionProcedure = "/graphene.management.v1.RevisionsAPI/RunRevision"
)

// RevisionsAPIClient is a client for the graphene.management.v1.RevisionsAPI service.
type RevisionsAPIClient interface {
	// Materialize STREAMS progress: a source build takes minutes, and a
	// silent request dies on the first idle NAT between the client and
	// the door. The stream is also the Studio build log.
	Materialize(context.Context, *connect.Request[v1.MaterializeRequest]) (*connect.ServerStreamForClient[v1.MaterializeEvent], error)
	RunRevision(context.Context, *connect.Request[v1.RunRevisionRequest]) (*connect.Response[v1.RunRevisionResponse], error)
}

// NewRevisionsAPIClient constructs a client for the graphene.management.v1.RevisionsAPI service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewRevisionsAPIClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) RevisionsAPIClient {
	baseURL = strings.TrimRight(baseURL, "/")
	revisionsAPIMethods := v1.File_proto_management_v1_revisions_proto.Services().ByName("RevisionsAPI").Methods()
	return &revisionsAPIClient{
		materialize: connect.NewClient[v1.MaterializeRequest, v1.MaterializeEvent](
			httpClient,
			baseURL+RevisionsAPIMaterializeProcedure,
			connect.WithSchema(revisionsAPIMethods.ByName("Materialize")),
			connect.WithClientOptions(opts...),
		),
		runRevision: connect.NewClient[v1.RunRevisionRequest, v1.RunRevisionResponse](
			httpClient,
			baseURL+RevisionsAPIRunRevisionProcedure,
			connect.WithSchema(revisionsAPIMethods.ByName("RunRevision")),
			connect.WithClientOptions(opts...),
		),
	}
}

// revisionsAPIClient implements RevisionsAPIClient.
type revisionsAPIClient struct {
	materialize *connect.Client[v1.MaterializeRequest, v1.MaterializeEvent]
	runRevision *connect.Client[v1.RunRevisionRequest, v1.RunRevisionResponse]
}

// Materialize calls graphene.management.v1.RevisionsAPI.Materialize.
func (c *revisionsAPIClient) Materialize(ctx context.Context, req *connect.Request[v1.MaterializeRequest]) (*connect.ServerStreamForClient[v1.MaterializeEvent], error) {
	return c.materialize.CallServerStream(ctx, req)
}

// RunRevision calls graphene.management.v1.RevisionsAPI.RunRevision.
func (c *revisionsAPIClient) RunRevision(ctx context.Context, req *connect.Request[v1.RunRevisionRequest]) (*connect.Response[v1.RunRevisionResponse], error) {
	return c.runRevision.CallUnary(ctx, req)
}

// RevisionsAPIHandler is an implementation of the graphene.management.v1.RevisionsAPI service.
type RevisionsAPIHandler interface {
	// Materialize STREAMS progress: a source build takes minutes, and a
	// silent request dies on the first idle NAT between the client and
	// the door. The stream is also the Studio build log.
	Materialize(context.Context, *connect.Request[v1.MaterializeRequest], *connect.ServerStream[v1.MaterializeEvent]) error
	RunRevision(context.Context, *connect.Request[v1.RunRevisionRequest]) (*connect.Response[v1.RunRevisionResponse], error)
}

// NewRevisionsAPIHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewRevisionsAPIHandler(svc RevisionsAPIHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	revisionsAPIMethods := v1.File_proto_management_v1_revisions_proto.Services().ByName("RevisionsAPI").Methods()
	revisionsAPIMaterializeHandler := connect.NewServerStreamHandler(
		RevisionsAPIMaterializeProcedure,
		svc.Materialize,
		connect.WithSchema(revisionsAPIMethods.ByName("Materialize")),
		connect.WithHandlerOptions(opts...),
	)
	revisionsAPIRunRevisionHandler := connect.NewUnaryHandler(
		RevisionsAPIRunRevisionProcedure,
		svc.RunRevision,
		connect.WithSchema(revisionsAPIMethods.ByName("RunRevision")),
		connect.WithHandlerOptions(opts...),
	)
	return "/graphene.management.v1.RevisionsAPI/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case RevisionsAPIMaterializeProcedure:
			revisionsAPIMaterializeHandler.ServeHTTP(w, r)
		case RevisionsAPIRunRevisionProcedure:
			revisionsAPIRunRevisionHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedRevisionsAPIHandler returns CodeUnimplemented from all methods.
type UnimplementedRevisionsAPIHandler struct{}

func (UnimplementedRevisionsAPIHandler) Materialize(context.Context, *connect.Request[v1.MaterializeRequest], *connect.ServerStream[v1.MaterializeEvent]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("graphene.management.v1.RevisionsAPI.Materialize is not implemented"))
}

func (UnimplementedRevisionsAPIHandler) RunRevision(context.Context, *connect.Request[v1.RunRevisionRequest]) (*connect.Response[v1.RunRevisionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("graphene.management.v1.RevisionsAPI.RunRevision is not implemented"))
}
