// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/management/v1/secrets.proto

package managementv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/graphene-ci/graphene/pkg/proto/management/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// SecretsAPIName is the fully-qualified name of the SecretsAPI service.
	SecretsAPIName = "graphene.management.v1.SecretsAPI"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SecretsAPISetSecretProcedure is the fully-qualified name of the SecretsAPI's SetSecret RPC.
	SecretsAPISetSecretProcedure = "/graphene.management.v1.SecretsAPI/SetSecret"
)

// SecretsAPIClient is a client for the graphene.management.v1.SecretsAPI service.
type SecretsAPIClient interface {
	SetSecret(context.Context, *connect.Request[v1.SetSecretRequest]) (*connect.Response[v1.SetSecretResponse], error)
}

// NewSecretsAPIClient constructs a client for the graphene.management.v1.SecretsAPI service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSecretsAPIClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SecretsAPIClient {
	baseURL = strings.TrimRight(baseURL, "/")
	secretsAPIMethods := v1.File_proto_management_v1_secrets_proto.Services().ByName("SecretsAPI").Methods()
	return &secretsAPIClient{
		setSecret: connect.NewClient[v1.SetSecretRequest, v1.SetSecretResponse](
			httpClient,
			baseURL+SecretsAPISetSecretProcedure,
			connect.WithSchema(secretsAPIMethods.ByName("SetSecret")),
			connect.WithClientOptions(opts...),
		),
	}
}

// secretsAPIClient implements SecretsAPIClient.
type secretsAPIClient struct {
	setSecret *connect.Client[v1.SetSecretRequest, v1.SetSecretResponse]
}

// SetSecret calls graphene.management.v1.SecretsAPI.SetSecret.
func (c *secretsAPIClient) SetSecret(ctx context.Context, req *connect.Request[v1.SetSecretRequest]) (*connect.Response[v1.SetSecretResponse], error) {
	return c.setSecret.CallUnary(ctx, req)
}

// SecretsAPIHandler is an implementation of the graphene.management.v1.SecretsAPI service.
type SecretsAPIHandler interface {
	SetSecret(context.Context, *connect.Request[v1.SetSecretRequest]) (*connect.Response[v1.SetSecretResponse], error)
}

// NewSecretsAPIHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSecretsAPIHandler(svc SecretsAPIHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	secretsAPIMethods := v1.File_proto_management_v1_secrets_proto.Services().ByName("SecretsAPI").Methods()
	secretsAPISetSecretHandler := connect.NewUnaryHandler(
		SecretsAPISetSecretProcedure,
		svc.SetSecret,
		connect.WithSchema(secretsAPIMethods.ByName("SetSecret")),
		connect.WithHandlerOptions(opts...),
	)
	return "/graphene.management.v1.SecretsAPI/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SecretsAPISetSecretProcedure:
			secretsAPISetSecretHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSecretsAPIHandler returns CodeUnimplemented from all methods.
type UnimplementedSecretsAPIHandler struct{}

func (UnimplementedSecretsAPIHandler) SetSecret(context.Context, *connect.Request[v1.SetSecretRequest]) (*connect.Response[v1.SetSecretResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("graphene.management.v1.SecretsAPI.SetSecret is not implemented"))
}
