// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/management/v1/workspaces.proto

package managementv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/graphene-ci/graphene/pkg/proto/management/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// WorkspacesAPIName is the fully-qualified name of the WorkspacesAPI service.
	WorkspacesAPIName = "graphene.management.v1.WorkspacesAPI"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// WorkspacesAPICreateWorkspaceProcedure is the fully-qualified name of the WorkspacesAPI's
	// CreateWorkspace RPC.
	WorkspacesAPICreateWorkspaceProcedure = "/graphene.management.v1.WorkspacesAPI/CreateWorkspace"
	// WorkspacesAPISyncWorkspaceProcedure is the fully-qualified name of the WorkspacesAPI's
	// SyncWorkspace RPC.
	WorkspacesAPISyncWorkspaceProcedure = "/graphene.management.v1.WorkspacesAPI/SyncWorkspace"
	// WorkspacesAPIDownloadSourceProcedure is the fully-qualified name of the WorkspacesAPI's
	// DownloadSource RPC.
	WorkspacesAPIDownloadSourceProcedure = "/graphene.management.v1.WorkspacesAPI/DownloadSource"
	// WorkspacesAPIListRuntimesProcedure is the fully-qualified name of the WorkspacesAPI's
	// ListRuntimes RPC.
	WorkspacesAPIListRuntimesProcedure = "/graphene.management.v1.WorkspacesAPI/ListRuntimes"
	// WorkspacesAPIListFilesProcedure is the fully-qualified name of the WorkspacesAPI's ListFiles RPC.
	WorkspacesAPIListFilesProcedure = "/graphene.management.v1.WorkspacesAPI/ListFiles"
	// WorkspacesAPIReadFileProcedure is the fully-qualified name of the WorkspacesAPI's ReadFile RPC.
	WorkspacesAPIReadFileProcedure = "/graphene.management.v1.WorkspacesAPI/ReadFile"
	// WorkspacesAPIWriteFileProcedure is the fully-qualified name of the WorkspacesAPI's WriteFile RPC.
	WorkspacesAPIWriteFileProcedure = "/graphene.management.v1.WorkspacesAPI/WriteFile"
	// WorkspacesAPIDeleteFileProcedure is the fully-qualified name of the WorkspacesAPI's DeleteFile
	// RPC.
	WorkspacesAPIDeleteFileProcedure = "/graphene.management.v1.WorkspacesAPI/DeleteFile"
)

// WorkspacesAPIClient is a client for the graphene.management.v1.WorkspacesAPI service.
type WorkspacesAPIClient interface {
	CreateWorkspace(context.Context, *connect.Request[v1.CreateWorkspaceRequest]) (*connect.Response[v1.CreateWorkspaceResponse], error)
	// SyncWorkspace re-resolves the source: a Git workspace fetches its
	// ref again, a snapshot workspace takes a freshly uploaded tree.
	SyncWorkspace(context.Context, *connect.Request[v1.SyncWorkspaceRequest]) (*connect.Response[v1.SyncWorkspaceResponse], error)
	// DownloadSource hands back the workspace's current working tree.
	DownloadSource(context.Context, *connect.Request[v1.DownloadSourceRequest]) (*connect.ServerStreamForClient[v1.DownloadSourceChunk], error)
	// ListRuntimes answers "which languages can I write a pipeline in
	// on THIS installation".
	ListRuntimes(context.Context, *connect.Request[v1.ListRuntimesRequest]) (*connect.Response[v1.ListRuntimesResponse], error)
	// The working tree is EDITABLE: Studio reads and writes files
	// straight into the workspace, and every write is durable — that is
	// the whole point of the tree living on the server.
	ListFiles(context.Context, *connect.Request[v1.ListFilesRequest]) (*connect.Response[v1.ListFilesResponse], error)
	ReadFile(context.Context, *connect.Request[v1.ReadFileRequest]) (*connect.Response[v1.ReadFileResponse], error)
	WriteFile(context.Context, *connect.Request[v1.WriteFileRequest]) (*connect.Response[v1.WriteFileResponse], error)
	DeleteFile(context.Context, *connect.Request[v1.DeleteFileRequest]) (*connect.Response[v1.WriteFileResponse], error)
}

// NewWorkspacesAPIClient constructs a client for the graphene.management.v1.WorkspacesAPI service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewWorkspacesAPIClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) WorkspacesAPIClient {
	baseURL = strings.TrimRight(baseURL, "/")
	workspacesAPIMethods := v1.File_proto_management_v1_workspaces_proto.Services().ByName("WorkspacesAPI").Methods()
	return &workspacesAPIClient{
		createWorkspace: connect.NewClient[v1.CreateWorkspaceRequest, v1.CreateWorkspaceResponse](
			httpClient,
			baseURL+WorkspacesAPICreateWorkspaceProcedure,
			connect.WithSchema(workspacesAPIMethods.ByName("CreateWorkspace")),
			connect.WithClientOptions(opts...),
		),
		syncWorkspace: connect.NewClient[v1.SyncWorkspaceRequest, v1.SyncWorkspaceResponse](
			httpClient,
			baseURL+WorkspacesAPISyncWorkspaceProcedure,
			connect.WithSchema(workspacesAPIMethods.ByName("SyncWorkspace")),
			connect.WithClientOptions(opts...),
		),
		downloadSource: connect.NewClient[v1.DownloadSourceRequest, v1.DownloadSourceChunk](
			httpClient,
			baseURL+WorkspacesAPIDownloadSourceProcedure,
			connect.WithSchema(workspacesAPIMethods.ByName("DownloadSource")),
			connect.WithClientOptions(opts...),
		),
		listRuntimes: connect.NewClient[v1.ListRuntimesRequest, v1.ListRuntimesResponse](
			httpClient,
			baseURL+WorkspacesAPIListRuntimesProcedure,
			connect.WithSchema(workspacesAPIMethods.ByName("ListRuntimes")),
			connect.WithClientOptions(opts...),
		),
		listFiles: connect.NewClient[v1.ListFilesRequest, v1.ListFilesResponse](
			httpClient,
			baseURL+WorkspacesAPIListFilesProcedure,
			connect.WithSchema(workspacesAPIMethods.ByName("ListFiles")),
			connect.WithClientOptions(opts...),
		),
		readFile: connect.NewClient[v1.ReadFileRequest, v1.ReadFileResponse](
			httpClient,
			baseURL+WorkspacesAPIReadFileProcedure,
			connect.WithSchema(workspacesAPIMethods.ByName("ReadFile")),
			connect.WithClientOptions(opts...),
		),
		writeFile: connect.NewClient[v1.WriteFileRequest, v1.WriteFileResponse](
			httpClient,
			baseURL+WorkspacesAPIWriteFileProcedure,
			connect.WithSchema(workspacesAPIMethods.ByName("WriteFile")),
			connect.WithClientOptions(opts...),
		),
		deleteFile: connect.NewClient[v1.DeleteFileRequest, v1.WriteFileResponse](
			httpClient,
			baseURL+WorkspacesAPIDeleteFileProcedure,
			connect.WithSchema(workspacesAPIMethods.ByName("DeleteFile")),
			connect.WithClientOptions(opts...),
		),
	}
}

// workspacesAPIClient implements WorkspacesAPIClient.
type workspacesAPIClient struct {
	createWorkspace *connect.Client[v1.CreateWorkspaceRequest, v1.CreateWorkspaceResponse]
	syncWorkspace   *connect.Client[v1.SyncWorkspaceRequest, v1.SyncWorkspaceResponse]
	downloadSource  *connect.Client[v1.DownloadSourceRequest, v1.DownloadSourceChunk]
	listRuntimes    *connect.Client[v1.ListRuntimesRequest, v1.ListRuntimesResponse]
	listFiles       *connect.Client[v1.ListFilesRequest, v1.ListFilesResponse]
	readFile        *connect.Client[v1.ReadFileRequest, v1.ReadFileResponse]
	writeFile       *connect.Client[v1.WriteFileRequest, v1.WriteFileResponse]
	deleteFile      *connect.Client[v1.DeleteFileRequest, v1.WriteFileResponse]
}

// CreateWorkspace calls graphene.management.v1.WorkspacesAPI.CreateWorkspace.
func (c *workspacesAPIClient) CreateWorkspace(ctx context.Context, req *connect.Request[v1.CreateWorkspaceRequest]) (*connect.Response[v1.CreateWorkspaceResponse], error) {
	return c.createWorkspace.CallUnary(ctx, req)
}

// SyncWorkspace calls graphene.management.v1.WorkspacesAPI.SyncWorkspace.
func (c *workspacesAPIClient) SyncWorkspace(ctx context.Context, req *connect.Request[v1.SyncWorkspaceRequest]) (*connect.Response[v1.SyncWorkspaceResponse], error) {
	return c.syncWorkspace.CallUnary(ctx, req)
}

// DownloadSource calls graphene.management.v1.WorkspacesAPI.DownloadSource.
func (c *workspacesAPIClient) DownloadSource(ctx context.Context, req *connect.Request[v1.DownloadSourceRequest]) (*connect.ServerStreamForClient[v1.DownloadSourceChunk], error) {
	return c.downloadSource.CallServerStream(ctx, req)
}

// ListRuntimes calls graphene.management.v1.WorkspacesAPI.ListRuntimes.
func (c *workspacesAPIClient) ListRuntimes(ctx context.Context, req *connect.Request[v1.ListRuntimesRequest]) (*connect.Response[v1.ListRuntimesResponse], error) {
	return c.listRuntimes.CallUnary(ctx, req)
}

// ListFiles calls graphene.management.v1.WorkspacesAPI.ListFiles.
func (c *workspacesAPIClient) ListFiles(ctx context.Context, req *connect.Request[v1.ListFilesRequest]) (*connect.Response[v1.ListFilesResponse], error) {
	return c.listFiles.CallUnary(ctx, req)
}

// ReadFile calls graphene.management.v1.WorkspacesAPI.ReadFile.
func (c *workspacesAPIClient) ReadFile(ctx context.Context, req *connect.Request[v1.ReadFileRequest]) (*connect.Response[v1.ReadFileResponse], error) {
	return c.readFile.CallUnary(ctx, req)
}

// WriteFile calls graphene.management.v1.WorkspacesAPI.WriteFile.
func (c *workspacesAPIClient) WriteFile(ctx context.Context, req *connect.Request[v1.WriteFileRequest]) (*connect.Response[v1.WriteFileResponse], error) {
	return c.writeFile.CallUnary(ctx, req)
}

// DeleteFile calls graphene.management.v1.WorkspacesAPI.DeleteFile.
func (c *workspacesAPIClient) DeleteFile(ctx context.Context, req *connect.Request[v1.DeleteFileRequest]) (*connect.Response[v1.WriteFileResponse], error) {
	return c.deleteFile.CallUnary(ctx, req)
}

// WorkspacesAPIHandler is an implementation of the graphene.management.v1.WorkspacesAPI service.
type WorkspacesAPIHandler interface {
	CreateWorkspace(context.Context, *connect.Request[v1.CreateWorkspaceRequest]) (*connect.Response[v1.CreateWorkspaceResponse], error)
	// SyncWorkspace re-resolves the source: a Git workspace fetches its
	// ref again, a snapshot workspace takes a freshly uploaded tree.
	SyncWorkspace(context.Context, *connect.Request[v1.SyncWorkspaceRequest]) (*connect.Response[v1.SyncWorkspaceResponse], error)
	// DownloadSource hands back the workspace's current working tree.
	DownloadSource(context.Context, *connect.Request[v1.DownloadSourceRequest], *connect.ServerStream[v1.DownloadSourceChunk]) error
	// ListRuntimes answers "which languages can I write a pipeline in
	// on THIS installation".
	ListRuntimes(context.Context, *connect.Request[v1.ListRuntimesRequest]) (*connect.Response[v1.ListRuntimesResponse], error)
	// The working tree is EDITABLE: Studio reads and writes files
	// straight into the workspace, and every write is durable — that is
	// the whole point of the tree living on the server.
	ListFiles(context.Context, *connect.Request[v1.ListFilesRequest]) (*connect.Response[v1.ListFilesResponse], error)
	ReadFile(context.Context, *connect.Request[v1.ReadFileRequest]) (*connect.Response[v1.ReadFileResponse], error)
	WriteFile(context.Context, *connect.Request[v1.WriteFileRequest]) (*connect.Response[v1.WriteFileResponse], error)
	DeleteFile(context.Context, *connect.Request[v1.DeleteFileRequest]) (*connect.Response[v1.WriteFileResponse], error)
}

// NewWorkspacesAPIHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewWorkspacesAPIHandler(svc WorkspacesAPIHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	workspacesAPIMethods := v1.File_proto_management_v1_workspaces_proto.Services().ByName("WorkspacesAPI").Methods()
	workspacesAPICreateWorkspaceHandler := connect.NewUnaryHandler(
		WorkspacesAPICreateWorkspaceProcedure,
		svc.CreateWorkspace,
		connect.WithSchema(workspacesAPIMethods.ByName("CreateWorkspace")),
		connect.WithHandlerOptions(opts...),
	)
	workspacesAPISyncWorkspaceHandler := connect.NewUnaryHandler(
		WorkspacesAPISyncWorkspaceProcedure,
		svc.SyncWorkspace,
		connect.WithSchema(workspacesAPIMethods.ByName("SyncWorkspace")),
		connect.WithHandlerOptions(opts...),
	)
	workspacesAPIDownloadSourceHandler := connect.NewServerStreamHandler(
		WorkspacesAPIDownloadSourceProcedure,
		svc.DownloadSource,
		connect.WithSchema(workspacesAPIMethods.ByName("DownloadSource")),
		connect.WithHandlerOptions(opts...),
	)
	workspacesAPIListRuntimesHandler := connect.NewUnaryHandler(
		WorkspacesAPIListRuntimesProcedure,
		svc.ListRuntimes,
		connect.WithSchema(workspacesAPIMethods.ByName("ListRuntimes")),
		connect.WithHandlerOptions(opts...),
	)
	workspacesAPIListFilesHandler := connect.NewUnaryHandler(
		WorkspacesAPIListFilesProcedure,
		svc.ListFiles,
		connect.WithSchema(workspacesAPIMethods.ByName("ListFiles")),
		connect.WithHandlerOptions(opts...),
	)
	workspacesAPIReadFileHandler := connect.NewUnaryHandler(
		WorkspacesAPIReadFileProcedure,
		svc.ReadFile,
		connect.WithSchema(workspacesAPIMethods.ByName("ReadFile")),
		connect.WithHandlerOptions(opts...),
	)
	workspacesAPIWriteFileHandler := connect.NewUnaryHandler(
		WorkspacesAPIWriteFileProcedure,
		svc.WriteFile,
		connect.WithSchema(workspacesAPIMethods.ByName("WriteFile")),
		connect.WithHandlerOptions(opts...),
	)
	workspacesAPIDeleteFileHandler := connect.NewUnaryHandler(
		WorkspacesAPIDeleteFileProcedure,
		svc.DeleteFile,
		connect.WithSchema(workspacesAPIMethods.ByName("DeleteFile")),
		connect.WithHandlerOptions(opts...),
	)
	return "/graphene.management.v1.WorkspacesAPI/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case WorkspacesAPICreateWorkspaceProcedure:
			workspacesAPICreateWorkspaceHandler.ServeHTTP(w, r)
		case WorkspacesAPISyncWorkspaceProcedure:
			workspacesAPISyncWorkspaceHandler.ServeHTTP(w, r)
		case WorkspacesAPIDownloadSourceProcedure:
			workspacesAPIDownloadSourceHandler.ServeHTTP(w, r)
		case WorkspacesAPIListRuntimesProcedure:
			workspacesAPIListRuntimesHandler.ServeHTTP(w, r)
		case WorkspacesAPIListFilesProcedure:
			workspacesAPIListFilesHandler.ServeHTTP(w, r)
		case WorkspacesAPIReadFileProcedure:
			workspacesAPIReadFileHandler.ServeHTTP(w, r)
		case WorkspacesAPIWriteFileProcedure:
			workspacesAPIWriteFileHandler.ServeHTTP(w, r)
		case WorkspacesAPIDeleteFileProcedure:
			workspacesAPIDeleteFileHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedWorkspacesAPIHandler returns CodeUnimplemented from all methods.
type UnimplementedWorkspacesAPIHandler struct{}

func (UnimplementedWorkspacesAPIHandler) CreateWorkspace(context.Context, *connect.Request[v1.CreateWorkspaceRequest]) (*connect.Response[v1.CreateWorkspaceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("graphene.management.v1.WorkspacesAPI.CreateWorkspace is not implemented"))
}

func (UnimplementedWorkspacesAPIHandler) SyncWorkspace(context.Context, *connect.Request[v1.SyncWorkspaceRequest]) (*connect.Response[v1.SyncWorkspaceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("graphene.management.v1.WorkspacesAPI.SyncWorkspace is not implemented"))
}

func (UnimplementedWorkspacesAPIHandler) DownloadSource(context.Context, *connect.Request[v1.DownloadSourceRequest], *connect.ServerStream[v1.DownloadSourceChunk]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("graphene.management.v1.WorkspacesAPI.DownloadSource is not implemented"))
}

func (UnimplementedWorkspacesAPIHandler) ListRuntimes(context.Context, *connect.Request[v1.ListRuntimesRequest]) (*connect.Response[v1.ListRuntimesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("graphene.management.v1.WorkspacesAPI.ListRuntimes is not implemented"))
}

func (UnimplementedWorkspacesAPIHandler) ListFiles(context.Context, *connect.Request[v1.ListFilesRequest]) (*connect.Response[v1.ListFilesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("graphene.management.v1.WorkspacesAPI.ListFiles is not implemented"))
}

func (UnimplementedWorkspacesAPIHandler) ReadFile(context.Context, *connect.Request[v1.ReadFileRequest]) (*connect.Response[v1.ReadFileResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("graphene.management.v1.WorkspacesAPI.ReadFile is not implemented"))
}

func (UnimplementedWorkspacesAPIHandler) WriteFile(context.Context, *connect.Request[v1.WriteFileRequest]) (*connect.Response[v1.WriteFileResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("graphene.management.v1.WorkspacesAPI.WriteFile is not implemented"))
}

func (UnimplementedWorkspacesAPIHandler) DeleteFile(context.Context, *connect.Request[v1.DeleteFileRequest]) (*connect.Response[v1.WriteFileResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("graphene.management.v1.WorkspacesAPI.DeleteFile is not implemented"))
}
