package install

import (
	"bytes"
	"fmt"
	"text/template"
)

// unitTemplate is the systemd service.
//
// The sandboxing is NOT system-only: a user manager applies these
// directives too (verified by running a unit carrying them), and they take
// the exposure level from "unsafe" to "medium" — so a workstation kernel
// is confined as well as a machine one. Only two directives are genuinely
// privileged: StateDirectory (the system data path is systemd's to own)
// and ProtectHome, which would hide the very directory a user-scope
// kernel stores its data in.
//
// ProtectSystem=strict makes everything read-only except ReadWritePaths
// and the runtime directory systemd creates for the socket.
const unitTemplate = `[Unit]
Description=Graphene kernel
Documentation=https://github.com/graphene-ci
After=network.target

[Service]
Type=simple
ExecStart={{ .Binary }} kernel run --config {{ .Config }}
Restart=on-failure
RestartSec=2s
KillSignal=SIGTERM
TimeoutStopSec=30s
RuntimeDirectory=graphen
RuntimeDirectoryMode=0750
UMask=0077
NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=strict
ReadWritePaths={{ .Data }}
ProtectKernelTunables=true
ProtectKernelModules=true
ProtectControlGroups=true
RestrictNamespaces=true
RestrictSUIDSGID=true
LockPersonality=true
MemoryDenyWriteExecute=true
SystemCallFilter=@system-service
SystemCallErrorNumber=EPERM
{{- if .System }}
StateDirectory=graphen
StateDirectoryMode=0750
ProtectHome=true
{{- end }}

[Install]
WantedBy={{ .WantedBy }}
`

// RenderUnit produces the unit file for a layout.
func RenderUnit(layout *Layout) ([]byte, error) {
	wantedBy := "default.target"
	if layout.Scope == ScopeSystem {
		wantedBy = "multi-user.target"
	}

	data := struct {
		Binary   string
		Config   string
		Data     string
		System   bool
		WantedBy string
	}{
		Binary:   layout.Binary,
		Config:   layout.Config,
		Data:     layout.Data,
		System:   layout.Scope == ScopeSystem,
		WantedBy: wantedBy,
	}

	tmpl, err := template.New("unit").Parse(unitTemplate)
	if err != nil {
		return nil, fmt.Errorf("install: unit template: %w", err)
	}

	var out bytes.Buffer
	if err := tmpl.Execute(&out, data); err != nil {
		return nil, fmt.Errorf("install: render unit: %w", err)
	}

	return out.Bytes(), nil
}

// configTemplate is the kernel configuration a fresh install starts with:
// a control kernel serving its socket, with the bootstrap credential read
// from a file so the secret never sits in the configuration itself.
const configTemplate = `# Generated by graphen kernel install.
data_dir: {{ .Data }}
identity:
  tenant: {{ .Tenant }}
  name: {{ .Name }}
log:
  level: info
  format: text
store: {}
blobs: {}
listen:
  uds: {{ .Socket }}
{{- if .TCP }}
  tcp: {{ .TCP }}
tls:
  mode: auto
{{- end }}
auth:
  bootstrap:
    name: bootstrap
    token:
      file: {{ .TokenFile }}
`

// ConfigOptions are the choices a fresh configuration needs.
type ConfigOptions struct {
	Tenant string
	Name   string
	TCP    string
}

// RenderConfig produces the configuration file for a layout.
func RenderConfig(layout *Layout, opts ConfigOptions) ([]byte, error) {
	data := struct {
		Data      string
		Tenant    string
		Name      string
		Socket    string
		TCP       string
		TokenFile string
	}{
		Data:      layout.Data,
		Tenant:    opts.Tenant,
		Name:      opts.Name,
		Socket:    layout.Socket,
		TCP:       opts.TCP,
		TokenFile: layout.TokenFile,
	}

	tmpl, err := template.New("config").Parse(configTemplate)
	if err != nil {
		return nil, fmt.Errorf("install: config template: %w", err)
	}

	var out bytes.Buffer
	if err := tmpl.Execute(&out, data); err != nil {
		return nil, fmt.Errorf("install: render config: %w", err)
	}

	return out.Bytes(), nil
}
