// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: proto/management/v1/namespaces.proto

package managementv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WhoamiRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WhoamiRequest) Reset() {
	*x = WhoamiRequest{}
	mi := &file_proto_management_v1_namespaces_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhoamiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhoamiRequest) ProtoMessage() {}

func (x *WhoamiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_v1_namespaces_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhoamiRequest.ProtoReflect.Descriptor instead.
func (*WhoamiRequest) Descriptor() ([]byte, []int) {
	return file_proto_management_v1_namespaces_proto_rawDescGZIP(), []int{0}
}

type WhoamiResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Role: admin | run | agent.
	Role string `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	// Namespace the token is scoped to; "*" — every namespace.
	Namespace     string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WhoamiResponse) Reset() {
	*x = WhoamiResponse{}
	mi := &file_proto_management_v1_namespaces_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhoamiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhoamiResponse) ProtoMessage() {}

func (x *WhoamiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_v1_namespaces_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhoamiResponse.ProtoReflect.Descriptor instead.
func (*WhoamiResponse) Descriptor() ([]byte, []int) {
	return file_proto_management_v1_namespaces_proto_rawDescGZIP(), []int{1}
}

func (x *WhoamiResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *WhoamiResponse) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type CreateNamespaceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// RetentionDays for closed workflows (default 30).
	RetentionDays int32 `protobuf:"varint,2,opt,name=retention_days,json=retentionDays,proto3" json:"retention_days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNamespaceRequest) Reset() {
	*x = CreateNamespaceRequest{}
	mi := &file_proto_management_v1_namespaces_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNamespaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNamespaceRequest) ProtoMessage() {}

func (x *CreateNamespaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_v1_namespaces_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNamespaceRequest.ProtoReflect.Descriptor instead.
func (*CreateNamespaceRequest) Descriptor() ([]byte, []int) {
	return file_proto_management_v1_namespaces_proto_rawDescGZIP(), []int{2}
}

func (x *CreateNamespaceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateNamespaceRequest) GetRetentionDays() int32 {
	if x != nil {
		return x.RetentionDays
	}
	return 0
}

type CreateNamespaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNamespaceResponse) Reset() {
	*x = CreateNamespaceResponse{}
	mi := &file_proto_management_v1_namespaces_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNamespaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNamespaceResponse) ProtoMessage() {}

func (x *CreateNamespaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_v1_namespaces_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNamespaceResponse.ProtoReflect.Descriptor instead.
func (*CreateNamespaceResponse) Descriptor() ([]byte, []int) {
	return file_proto_management_v1_namespaces_proto_rawDescGZIP(), []int{3}
}

type ListNamespacesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNamespacesRequest) Reset() {
	*x = ListNamespacesRequest{}
	mi := &file_proto_management_v1_namespaces_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNamespacesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNamespacesRequest) ProtoMessage() {}

func (x *ListNamespacesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_v1_namespaces_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNamespacesRequest.ProtoReflect.Descriptor instead.
func (*ListNamespacesRequest) Descriptor() ([]byte, []int) {
	return file_proto_management_v1_namespaces_proto_rawDescGZIP(), []int{4}
}

type ListNamespacesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Names         []string               `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNamespacesResponse) Reset() {
	*x = ListNamespacesResponse{}
	mi := &file_proto_management_v1_namespaces_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNamespacesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNamespacesResponse) ProtoMessage() {}

func (x *ListNamespacesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_v1_namespaces_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNamespacesResponse.ProtoReflect.Descriptor instead.
func (*ListNamespacesResponse) Descriptor() ([]byte, []int) {
	return file_proto_management_v1_namespaces_proto_rawDescGZIP(), []int{5}
}

func (x *ListNamespacesResponse) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

var File_proto_management_v1_namespaces_proto protoreflect.FileDescriptor

const file_proto_management_v1_namespaces_proto_rawDesc = "" +
	"\n" +
	"$proto/management/v1/namespaces.proto\x12\x16graphene.management.v1\"\x0f\n" +
	"\rWhoamiRequest\"B\n" +
	"\x0eWhoamiResponse\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\"S\n" +
	"\x16CreateNamespaceRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x0eretention_days\x18\x02 \x01(\x05R\rretentionDays\"\x19\n" +
	"\x17CreateNamespaceResponse\"\x17\n" +
	"\x15ListNamespacesRequest\".\n" +
	"\x16ListNamespacesResponse\x12\x14\n" +
	"\x05names\x18\x01 \x03(\tR\x05names2\xcd\x02\n" +
	"\rNamespacesAPI\x12r\n" +
	"\x0fCreateNamespace\x12..graphene.management.v1.CreateNamespaceRequest\x1a/.graphene.management.v1.CreateNamespaceResponse\x12o\n" +
	"\x0eListNamespaces\x12-.graphene.management.v1.ListNamespacesRequest\x1a..graphene.management.v1.ListNamespacesResponse\x12W\n" +
	"\x06Whoami\x12%.graphene.management.v1.WhoamiRequest\x1a&.graphene.management.v1.WhoamiResponseBFZDgithub.com/graphene-ci/graphene/pkg/proto/management/v1;managementv1b\x06proto3"

var (
	file_proto_management_v1_namespaces_proto_rawDescOnce sync.Once
	file_proto_management_v1_namespaces_proto_rawDescData []byte
)

func file_proto_management_v1_namespaces_proto_rawDescGZIP() []byte {
	file_proto_management_v1_namespaces_proto_rawDescOnce.Do(func() {
		file_proto_management_v1_namespaces_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_management_v1_namespaces_proto_rawDesc), len(file_proto_management_v1_namespaces_proto_rawDesc)))
	})
	return file_proto_management_v1_namespaces_proto_rawDescData
}

var file_proto_management_v1_namespaces_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_management_v1_namespaces_proto_goTypes = []any{
	(*WhoamiRequest)(nil),           // 0: graphene.management.v1.WhoamiRequest
	(*WhoamiResponse)(nil),          // 1: graphene.management.v1.WhoamiResponse
	(*CreateNamespaceRequest)(nil),  // 2: graphene.management.v1.CreateNamespaceRequest
	(*CreateNamespaceResponse)(nil), // 3: graphene.management.v1.CreateNamespaceResponse
	(*ListNamespacesRequest)(nil),   // 4: graphene.management.v1.ListNamespacesRequest
	(*ListNamespacesResponse)(nil),  // 5: graphene.management.v1.ListNamespacesResponse
}
var file_proto_management_v1_namespaces_proto_depIdxs = []int32{
	2, // 0: graphene.management.v1.NamespacesAPI.CreateNamespace:input_type -> graphene.management.v1.CreateNamespaceRequest
	4, // 1: graphene.management.v1.NamespacesAPI.ListNamespaces:input_type -> graphene.management.v1.ListNamespacesRequest
	0, // 2: graphene.management.v1.NamespacesAPI.Whoami:input_type -> graphene.management.v1.WhoamiRequest
	3, // 3: graphene.management.v1.NamespacesAPI.CreateNamespace:output_type -> graphene.management.v1.CreateNamespaceResponse
	5, // 4: graphene.management.v1.NamespacesAPI.ListNamespaces:output_type -> graphene.management.v1.ListNamespacesResponse
	1, // 5: graphene.management.v1.NamespacesAPI.Whoami:output_type -> graphene.management.v1.WhoamiResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_management_v1_namespaces_proto_init() }
func file_proto_management_v1_namespaces_proto_init() {
	if File_proto_management_v1_namespaces_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_management_v1_namespaces_proto_rawDesc), len(file_proto_management_v1_namespaces_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_management_v1_namespaces_proto_goTypes,
		DependencyIndexes: file_proto_management_v1_namespaces_proto_depIdxs,
		MessageInfos:      file_proto_management_v1_namespaces_proto_msgTypes,
	}.Build()
	File_proto_management_v1_namespaces_proto = out.File
	file_proto_management_v1_namespaces_proto_goTypes = nil
	file_proto_management_v1_namespaces_proto_depIdxs = nil
}
