// The five dimensions of any entity — state, events, logs, metrics,
// trace — behind ONE surface. State and events come from the plane of
// truth (Temporal: describes and workflow histories) and are complete
// by construction; logs, metrics, and traces come from the telemetry
// plane (OTel backend behind the collector) and are as complete as
// delivery was. Refs address anything: "run/x", "agent/vm-1",
// "vpc.network/net", "artifact/r".

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: proto/management/v1/observe.proto

package managementv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ObserveStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           string                 `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObserveStateRequest) Reset() {
	*x = ObserveStateRequest{}
	mi := &file_proto_management_v1_observe_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObserveStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObserveStateRequest) ProtoMessage() {}

func (x *ObserveStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_v1_observe_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObserveStateRequest.ProtoReflect.Descriptor instead.
func (*ObserveStateRequest) Descriptor() ([]byte, []int) {
	return file_proto_management_v1_observe_proto_rawDescGZIP(), []int{0}
}

func (x *ObserveStateRequest) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

type ObserveStateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Status is the workflow execution status (runs and entities alike).
	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// Resource is the full record for entity refs (describe); unset for
	// plain runs.
	Resource      *Resource `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObserveStateResponse) Reset() {
	*x = ObserveStateResponse{}
	mi := &file_proto_management_v1_observe_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObserveStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObserveStateResponse) ProtoMessage() {}

func (x *ObserveStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_v1_observe_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObserveStateResponse.ProtoReflect.Descriptor instead.
func (*ObserveStateResponse) Descriptor() ([]byte, []int) {
	return file_proto_management_v1_observe_proto_rawDescGZIP(), []int{1}
}

func (x *ObserveStateResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ObserveStateResponse) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

type EventsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Ref   string                 `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	// Resume: emit only events after this history event id.
	AfterEventId int64 `protobuf:"varint,2,opt,name=after_event_id,json=afterEventId,proto3" json:"after_event_id,omitempty"`
	// Follow keeps the stream open for new events until the workflow
	// closes (or forever, for a living entity).
	Follow bool `protobuf:"varint,3,opt,name=follow,proto3" json:"follow,omitempty"`
	// ActivityId slices the stream to one activity execution.
	ActivityId    string `protobuf:"bytes,4,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventsRequest) Reset() {
	*x = EventsRequest{}
	mi := &file_proto_management_v1_observe_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventsRequest) ProtoMessage() {}

func (x *EventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_v1_observe_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventsRequest.ProtoReflect.Descriptor instead.
func (*EventsRequest) Descriptor() ([]byte, []int) {
	return file_proto_management_v1_observe_proto_rawDescGZIP(), []int{2}
}

func (x *EventsRequest) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *EventsRequest) GetAfterEventId() int64 {
	if x != nil {
		return x.AfterEventId
	}
	return 0
}

func (x *EventsRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

func (x *EventsRequest) GetActivityId() string {
	if x != nil {
		return x.ActivityId
	}
	return ""
}

type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// EventId is the stable cursor: the Temporal history event id.
	EventId      int64 `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	TimeUnixNano int64 `protobuf:"varint,2,opt,name=time_unix_nano,json=timeUnixNano,proto3" json:"time_unix_nano,omitempty"`
	// Kind classifies for rendering: run-started, activity-scheduled,
	// activity-completed, activity-failed, command-received,
	// internal-<type>, ... Nothing is omitted — unclassified history
	// events pass through as internal-*.
	Kind string `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	// Subject: the activity/command name the event is about.
	Subject string `protobuf:"bytes,4,opt,name=subject,proto3" json:"subject,omitempty"`
	// Agent executing it, when the task queue names one.
	Agent   string `protobuf:"bytes,5,opt,name=agent,proto3" json:"agent,omitempty"`
	Status  string `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Error   string `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	Attempt int32  `protobuf:"varint,8,opt,name=attempt,proto3" json:"attempt,omitempty"`
	// Input/result payloads as JSON — history is secret-free by
	// construction (secrets travel as names), so nothing is stripped.
	Input  []byte `protobuf:"bytes,9,opt,name=input,proto3" json:"input,omitempty"`
	Result []byte `protobuf:"bytes,10,opt,name=result,proto3" json:"result,omitempty"`
	// Raw is the entire history event (protojson) for drill-down.
	Raw           []byte `protobuf:"bytes,11,opt,name=raw,proto3" json:"raw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_proto_management_v1_observe_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_v1_observe_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_proto_management_v1_observe_proto_rawDescGZIP(), []int{3}
}

func (x *Event) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *Event) GetTimeUnixNano() int64 {
	if x != nil {
		return x.TimeUnixNano
	}
	return 0
}

func (x *Event) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Event) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Event) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

func (x *Event) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Event) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Event) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *Event) GetInput() []byte {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *Event) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *Event) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

type LogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           string                 `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	Follow        bool                   `protobuf:"varint,2,opt,name=follow,proto3" json:"follow,omitempty"`
	SinceUnixNano int64                  `protobuf:"varint,3,opt,name=since_unix_nano,json=sinceUnixNano,proto3" json:"since_unix_nano,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsRequest) Reset() {
	*x = LogsRequest{}
	mi := &file_proto_management_v1_observe_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsRequest) ProtoMessage() {}

func (x *LogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_v1_observe_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsRequest.ProtoReflect.Descriptor instead.
func (*LogsRequest) Descriptor() ([]byte, []int) {
	return file_proto_management_v1_observe_proto_rawDescGZIP(), []int{4}
}

func (x *LogsRequest) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *LogsRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

func (x *LogsRequest) GetSinceUnixNano() int64 {
	if x != nil {
		return x.SinceUnixNano
	}
	return 0
}

type LogRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimeUnixNano  int64                  `protobuf:"varint,1,opt,name=time_unix_nano,json=timeUnixNano,proto3" json:"time_unix_nano,omitempty"`
	Severity      string                 `protobuf:"bytes,2,opt,name=severity,proto3" json:"severity,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Attributes    map[string]string      `protobuf:"bytes,4,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogRecord) Reset() {
	*x = LogRecord{}
	mi := &file_proto_management_v1_observe_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRecord) ProtoMessage() {}

func (x *LogRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_v1_observe_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRecord.ProtoReflect.Descriptor instead.
func (*LogRecord) Descriptor() ([]byte, []int) {
	return file_proto_management_v1_observe_proto_rawDescGZIP(), []int{5}
}

func (x *LogRecord) GetTimeUnixNano() int64 {
	if x != nil {
		return x.TimeUnixNano
	}
	return 0
}

func (x *LogRecord) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *LogRecord) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *LogRecord) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type MetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           string                 `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	StartUnixNano int64                  `protobuf:"varint,2,opt,name=start_unix_nano,json=startUnixNano,proto3" json:"start_unix_nano,omitempty"`
	EndUnixNano   int64                  `protobuf:"varint,3,opt,name=end_unix_nano,json=endUnixNano,proto3" json:"end_unix_nano,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsRequest) Reset() {
	*x = MetricsRequest{}
	mi := &file_proto_management_v1_observe_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsRequest) ProtoMessage() {}

func (x *MetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_v1_observe_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsRequest.ProtoReflect.Descriptor instead.
func (*MetricsRequest) Descriptor() ([]byte, []int) {
	return file_proto_management_v1_observe_proto_rawDescGZIP(), []int{6}
}

func (x *MetricsRequest) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *MetricsRequest) GetStartUnixNano() int64 {
	if x != nil {
		return x.StartUnixNano
	}
	return 0
}

func (x *MetricsRequest) GetEndUnixNano() int64 {
	if x != nil {
		return x.EndUnixNano
	}
	return 0
}

type MetricsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Series is backend-shaped JSON; the contract firms up with the
	// chosen backend.
	Series        []byte `protobuf:"bytes,1,opt,name=series,proto3" json:"series,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsResponse) Reset() {
	*x = MetricsResponse{}
	mi := &file_proto_management_v1_observe_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsResponse) ProtoMessage() {}

func (x *MetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_v1_observe_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsResponse.ProtoReflect.Descriptor instead.
func (*MetricsResponse) Descriptor() ([]byte, []int) {
	return file_proto_management_v1_observe_proto_rawDescGZIP(), []int{7}
}

func (x *MetricsResponse) GetSeries() []byte {
	if x != nil {
		return x.Series
	}
	return nil
}

type TraceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           string                 `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TraceRequest) Reset() {
	*x = TraceRequest{}
	mi := &file_proto_management_v1_observe_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TraceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraceRequest) ProtoMessage() {}

func (x *TraceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_v1_observe_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraceRequest.ProtoReflect.Descriptor instead.
func (*TraceRequest) Descriptor() ([]byte, []int) {
	return file_proto_management_v1_observe_proto_rawDescGZIP(), []int{8}
}

func (x *TraceRequest) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

type TraceResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Trace is the span tree as JSON.
	Trace         []byte `protobuf:"bytes,1,opt,name=trace,proto3" json:"trace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TraceResponse) Reset() {
	*x = TraceResponse{}
	mi := &file_proto_management_v1_observe_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TraceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraceResponse) ProtoMessage() {}

func (x *TraceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_v1_observe_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraceResponse.ProtoReflect.Descriptor instead.
func (*TraceResponse) Descriptor() ([]byte, []int) {
	return file_proto_management_v1_observe_proto_rawDescGZIP(), []int{9}
}

func (x *TraceResponse) GetTrace() []byte {
	if x != nil {
		return x.Trace
	}
	return nil
}

var File_proto_management_v1_observe_proto protoreflect.FileDescriptor

const file_proto_management_v1_observe_proto_rawDesc = "" +
	"\n" +
	"!proto/management/v1/observe.proto\x12\x16graphene.management.v1\x1a#proto/management/v1/resources.proto\"'\n" +
	"\x13ObserveStateRequest\x12\x10\n" +
	"\x03ref\x18\x01 \x01(\tR\x03ref\"l\n" +
	"\x14ObserveStateResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12<\n" +
	"\bresource\x18\x02 \x01(\v2 .graphene.management.v1.ResourceR\bresource\"\x80\x01\n" +
	"\rEventsRequest\x12\x10\n" +
	"\x03ref\x18\x01 \x01(\tR\x03ref\x12$\n" +
	"\x0eafter_event_id\x18\x02 \x01(\x03R\fafterEventId\x12\x16\n" +
	"\x06follow\x18\x03 \x01(\bR\x06follow\x12\x1f\n" +
	"\vactivity_id\x18\x04 \x01(\tR\n" +
	"activityId\"\x94\x02\n" +
	"\x05Event\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\x03R\aeventId\x12$\n" +
	"\x0etime_unix_nano\x18\x02 \x01(\x03R\ftimeUnixNano\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x18\n" +
	"\asubject\x18\x04 \x01(\tR\asubject\x12\x14\n" +
	"\x05agent\x18\x05 \x01(\tR\x05agent\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\x12\x18\n" +
	"\aattempt\x18\b \x01(\x05R\aattempt\x12\x14\n" +
	"\x05input\x18\t \x01(\fR\x05input\x12\x16\n" +
	"\x06result\x18\n" +
	" \x01(\fR\x06result\x12\x10\n" +
	"\x03raw\x18\v \x01(\fR\x03raw\"_\n" +
	"\vLogsRequest\x12\x10\n" +
	"\x03ref\x18\x01 \x01(\tR\x03ref\x12\x16\n" +
	"\x06follow\x18\x02 \x01(\bR\x06follow\x12&\n" +
	"\x0fsince_unix_nano\x18\x03 \x01(\x03R\rsinceUnixNano\"\xf3\x01\n" +
	"\tLogRecord\x12$\n" +
	"\x0etime_unix_nano\x18\x01 \x01(\x03R\ftimeUnixNano\x12\x1a\n" +
	"\bseverity\x18\x02 \x01(\tR\bseverity\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x12Q\n" +
	"\n" +
	"attributes\x18\x04 \x03(\v21.graphene.management.v1.LogRecord.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"n\n" +
	"\x0eMetricsRequest\x12\x10\n" +
	"\x03ref\x18\x01 \x01(\tR\x03ref\x12&\n" +
	"\x0fstart_unix_nano\x18\x02 \x01(\x03R\rstartUnixNano\x12\"\n" +
	"\rend_unix_nano\x18\x03 \x01(\x03R\vendUnixNano\")\n" +
	"\x0fMetricsResponse\x12\x16\n" +
	"\x06series\x18\x01 \x01(\fR\x06series\" \n" +
	"\fTraceRequest\x12\x10\n" +
	"\x03ref\x18\x01 \x01(\tR\x03ref\"%\n" +
	"\rTraceResponse\x12\x14\n" +
	"\x05trace\x18\x01 \x01(\fR\x05trace2\xc6\x03\n" +
	"\n" +
	"ObserveAPI\x12b\n" +
	"\x05State\x12+.graphene.management.v1.ObserveStateRequest\x1a,.graphene.management.v1.ObserveStateResponse\x12P\n" +
	"\x06Events\x12%.graphene.management.v1.EventsRequest\x1a\x1d.graphene.management.v1.Event0\x01\x12P\n" +
	"\x04Logs\x12#.graphene.management.v1.LogsRequest\x1a!.graphene.management.v1.LogRecord0\x01\x12Z\n" +
	"\aMetrics\x12&.graphene.management.v1.MetricsRequest\x1a'.graphene.management.v1.MetricsResponse\x12T\n" +
	"\x05Trace\x12$.graphene.management.v1.TraceRequest\x1a%.graphene.management.v1.TraceResponseBFZDgithub.com/graphene-ci/graphene/pkg/proto/management/v1;managementv1b\x06proto3"

var (
	file_proto_management_v1_observe_proto_rawDescOnce sync.Once
	file_proto_management_v1_observe_proto_rawDescData []byte
)

func file_proto_management_v1_observe_proto_rawDescGZIP() []byte {
	file_proto_management_v1_observe_proto_rawDescOnce.Do(func() {
		file_proto_management_v1_observe_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_management_v1_observe_proto_rawDesc), len(file_proto_management_v1_observe_proto_rawDesc)))
	})
	return file_proto_management_v1_observe_proto_rawDescData
}

var file_proto_management_v1_observe_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_management_v1_observe_proto_goTypes = []any{
	(*ObserveStateRequest)(nil),  // 0: graphene.management.v1.ObserveStateRequest
	(*ObserveStateResponse)(nil), // 1: graphene.management.v1.ObserveStateResponse
	(*EventsRequest)(nil),        // 2: graphene.management.v1.EventsRequest
	(*Event)(nil),                // 3: graphene.management.v1.Event
	(*LogsRequest)(nil),          // 4: graphene.management.v1.LogsRequest
	(*LogRecord)(nil),            // 5: graphene.management.v1.LogRecord
	(*MetricsRequest)(nil),       // 6: graphene.management.v1.MetricsRequest
	(*MetricsResponse)(nil),      // 7: graphene.management.v1.MetricsResponse
	(*TraceRequest)(nil),         // 8: graphene.management.v1.TraceRequest
	(*TraceResponse)(nil),        // 9: graphene.management.v1.TraceResponse
	nil,                          // 10: graphene.management.v1.LogRecord.AttributesEntry
	(*Resource)(nil),             // 11: graphene.management.v1.Resource
}
var file_proto_management_v1_observe_proto_depIdxs = []int32{
	11, // 0: graphene.management.v1.ObserveStateResponse.resource:type_name -> graphene.management.v1.Resource
	10, // 1: graphene.management.v1.LogRecord.attributes:type_name -> graphene.management.v1.LogRecord.AttributesEntry
	0,  // 2: graphene.management.v1.ObserveAPI.State:input_type -> graphene.management.v1.ObserveStateRequest
	2,  // 3: graphene.management.v1.ObserveAPI.Events:input_type -> graphene.management.v1.EventsRequest
	4,  // 4: graphene.management.v1.ObserveAPI.Logs:input_type -> graphene.management.v1.LogsRequest
	6,  // 5: graphene.management.v1.ObserveAPI.Metrics:input_type -> graphene.management.v1.MetricsRequest
	8,  // 6: graphene.management.v1.ObserveAPI.Trace:input_type -> graphene.management.v1.TraceRequest
	1,  // 7: graphene.management.v1.ObserveAPI.State:output_type -> graphene.management.v1.ObserveStateResponse
	3,  // 8: graphene.management.v1.ObserveAPI.Events:output_type -> graphene.management.v1.Event
	5,  // 9: graphene.management.v1.ObserveAPI.Logs:output_type -> graphene.management.v1.LogRecord
	7,  // 10: graphene.management.v1.ObserveAPI.Metrics:output_type -> graphene.management.v1.MetricsResponse
	9,  // 11: graphene.management.v1.ObserveAPI.Trace:output_type -> graphene.management.v1.TraceResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_management_v1_observe_proto_init() }
func file_proto_management_v1_observe_proto_init() {
	if File_proto_management_v1_observe_proto != nil {
		return
	}
	file_proto_management_v1_resources_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_management_v1_observe_proto_rawDesc), len(file_proto_management_v1_observe_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_management_v1_observe_proto_goTypes,
		DependencyIndexes: file_proto_management_v1_observe_proto_depIdxs,
		MessageInfos:      file_proto_management_v1_observe_proto_msgTypes,
	}.Build()
	File_proto_management_v1_observe_proto = out.File
	file_proto_management_v1_observe_proto_goTypes = nil
	file_proto_management_v1_observe_proto_depIdxs = nil
}
