// The five dimensions of any entity — state, events, logs, metrics,
// trace — behind ONE surface. State and events come from the plane of
// truth (Temporal: describes and workflow histories) and are complete
// by construction; logs, metrics, and traces come from the telemetry
// plane (OTel backend behind the collector) and are as complete as
// delivery was. Refs address anything: "run/x", "agent/vm-1",
// "vpc.network/net", "artifact/r".

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: proto/management/v1/observe.proto

package managementv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ObserveAPI_State_FullMethodName   = "/graphene.management.v1.ObserveAPI/State"
	ObserveAPI_Events_FullMethodName  = "/graphene.management.v1.ObserveAPI/Events"
	ObserveAPI_Logs_FullMethodName    = "/graphene.management.v1.ObserveAPI/Logs"
	ObserveAPI_Metrics_FullMethodName = "/graphene.management.v1.ObserveAPI/Metrics"
	ObserveAPI_Trace_FullMethodName   = "/graphene.management.v1.ObserveAPI/Trace"
)

// ObserveAPIClient is the client API for ObserveAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ObserveAPIClient interface {
	// State is dimension 1: the full current record.
	State(ctx context.Context, in *ObserveStateRequest, opts ...grpc.CallOption) (*ObserveStateResponse, error)
	// Events is dimension 2: the entity's own history, translated —
	// classification without omission (raw carries everything).
	Events(ctx context.Context, in *EventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error)
	// Logs is dimension 3 (telemetry plane).
	Logs(ctx context.Context, in *LogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogRecord], error)
	// Metrics is dimension 4 (telemetry plane).
	Metrics(ctx context.Context, in *MetricsRequest, opts ...grpc.CallOption) (*MetricsResponse, error)
	// Trace is dimension 5 (telemetry plane).
	Trace(ctx context.Context, in *TraceRequest, opts ...grpc.CallOption) (*TraceResponse, error)
}

type observeAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewObserveAPIClient(cc grpc.ClientConnInterface) ObserveAPIClient {
	return &observeAPIClient{cc}
}

func (c *observeAPIClient) State(ctx context.Context, in *ObserveStateRequest, opts ...grpc.CallOption) (*ObserveStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ObserveStateResponse)
	err := c.cc.Invoke(ctx, ObserveAPI_State_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *observeAPIClient) Events(ctx context.Context, in *EventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ObserveAPI_ServiceDesc.Streams[0], ObserveAPI_Events_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EventsRequest, Event]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ObserveAPI_EventsClient = grpc.ServerStreamingClient[Event]

func (c *observeAPIClient) Logs(ctx context.Context, in *LogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogRecord], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ObserveAPI_ServiceDesc.Streams[1], ObserveAPI_Logs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LogsRequest, LogRecord]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ObserveAPI_LogsClient = grpc.ServerStreamingClient[LogRecord]

func (c *observeAPIClient) Metrics(ctx context.Context, in *MetricsRequest, opts ...grpc.CallOption) (*MetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MetricsResponse)
	err := c.cc.Invoke(ctx, ObserveAPI_Metrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *observeAPIClient) Trace(ctx context.Context, in *TraceRequest, opts ...grpc.CallOption) (*TraceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TraceResponse)
	err := c.cc.Invoke(ctx, ObserveAPI_Trace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ObserveAPIServer is the server API for ObserveAPI service.
// All implementations must embed UnimplementedObserveAPIServer
// for forward compatibility.
type ObserveAPIServer interface {
	// State is dimension 1: the full current record.
	State(context.Context, *ObserveStateRequest) (*ObserveStateResponse, error)
	// Events is dimension 2: the entity's own history, translated —
	// classification without omission (raw carries everything).
	Events(*EventsRequest, grpc.ServerStreamingServer[Event]) error
	// Logs is dimension 3 (telemetry plane).
	Logs(*LogsRequest, grpc.ServerStreamingServer[LogRecord]) error
	// Metrics is dimension 4 (telemetry plane).
	Metrics(context.Context, *MetricsRequest) (*MetricsResponse, error)
	// Trace is dimension 5 (telemetry plane).
	Trace(context.Context, *TraceRequest) (*TraceResponse, error)
	mustEmbedUnimplementedObserveAPIServer()
}

// UnimplementedObserveAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedObserveAPIServer struct{}

func (UnimplementedObserveAPIServer) State(context.Context, *ObserveStateRequest) (*ObserveStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method State not implemented")
}
func (UnimplementedObserveAPIServer) Events(*EventsRequest, grpc.ServerStreamingServer[Event]) error {
	return status.Error(codes.Unimplemented, "method Events not implemented")
}
func (UnimplementedObserveAPIServer) Logs(*LogsRequest, grpc.ServerStreamingServer[LogRecord]) error {
	return status.Error(codes.Unimplemented, "method Logs not implemented")
}
func (UnimplementedObserveAPIServer) Metrics(context.Context, *MetricsRequest) (*MetricsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Metrics not implemented")
}
func (UnimplementedObserveAPIServer) Trace(context.Context, *TraceRequest) (*TraceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Trace not implemented")
}
func (UnimplementedObserveAPIServer) mustEmbedUnimplementedObserveAPIServer() {}
func (UnimplementedObserveAPIServer) testEmbeddedByValue()                    {}

// UnsafeObserveAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ObserveAPIServer will
// result in compilation errors.
type UnsafeObserveAPIServer interface {
	mustEmbedUnimplementedObserveAPIServer()
}

func RegisterObserveAPIServer(s grpc.ServiceRegistrar, srv ObserveAPIServer) {
	// If the following call panics, it indicates UnimplementedObserveAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ObserveAPI_ServiceDesc, srv)
}

func _ObserveAPI_State_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObserveStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObserveAPIServer).State(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ObserveAPI_State_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObserveAPIServer).State(ctx, req.(*ObserveStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObserveAPI_Events_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ObserveAPIServer).Events(m, &grpc.GenericServerStream[EventsRequest, Event]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ObserveAPI_EventsServer = grpc.ServerStreamingServer[Event]

func _ObserveAPI_Logs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ObserveAPIServer).Logs(m, &grpc.GenericServerStream[LogsRequest, LogRecord]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ObserveAPI_LogsServer = grpc.ServerStreamingServer[LogRecord]

func _ObserveAPI_Metrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObserveAPIServer).Metrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ObserveAPI_Metrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObserveAPIServer).Metrics(ctx, req.(*MetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObserveAPI_Trace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TraceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObserveAPIServer).Trace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ObserveAPI_Trace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObserveAPIServer).Trace(ctx, req.(*TraceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ObserveAPI_ServiceDesc is the grpc.ServiceDesc for ObserveAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ObserveAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "graphene.management.v1.ObserveAPI",
	HandlerType: (*ObserveAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "State",
			Handler:    _ObserveAPI_State_Handler,
		},
		{
			MethodName: "Metrics",
			Handler:    _ObserveAPI_Metrics_Handler,
		},
		{
			MethodName: "Trace",
			Handler:    _ObserveAPI_Trace_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Events",
			Handler:       _ObserveAPI_Events_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Logs",
			Handler:       _ObserveAPI_Logs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/management/v1/observe.proto",
}
