// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: proto/management/v1/rbac.proto

package managementv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IssueTokenResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	TokenId string                 `protobuf:"bytes,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	// Token is the VALUE, returned once and never stored.
	Token         string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Expires       string `protobuf:"bytes,3,opt,name=expires,proto3" json:"expires,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueTokenResponse) Reset() {
	*x = IssueTokenResponse{}
	mi := &file_proto_management_v1_rbac_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueTokenResponse) ProtoMessage() {}

func (x *IssueTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_v1_rbac_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueTokenResponse.ProtoReflect.Descriptor instead.
func (*IssueTokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_management_v1_rbac_proto_rawDescGZIP(), []int{0}
}

func (x *IssueTokenResponse) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *IssueTokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *IssueTokenResponse) GetExpires() string {
	if x != nil {
		return x.Expires
	}
	return ""
}

type IssueTokenRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Account string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	// TtlSeconds bounds the token's life; 0 means until it is revoked.
	TtlSeconds    int64  `protobuf:"varint,2,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	Comment       string `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueTokenRequest) Reset() {
	*x = IssueTokenRequest{}
	mi := &file_proto_management_v1_rbac_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueTokenRequest) ProtoMessage() {}

func (x *IssueTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_v1_rbac_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueTokenRequest.ProtoReflect.Descriptor instead.
func (*IssueTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_management_v1_rbac_proto_rawDescGZIP(), []int{1}
}

func (x *IssueTokenRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *IssueTokenRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

func (x *IssueTokenRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type WhoAmIRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WhoAmIRequest) Reset() {
	*x = WhoAmIRequest{}
	mi := &file_proto_management_v1_rbac_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhoAmIRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhoAmIRequest) ProtoMessage() {}

func (x *WhoAmIRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_v1_rbac_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhoAmIRequest.ProtoReflect.Descriptor instead.
func (*WhoAmIRequest) Descriptor() ([]byte, []int) {
	return file_proto_management_v1_rbac_proto_rawDescGZIP(), []int{2}
}

type WhoAmIResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Subject   string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Groups    []string               `protobuf:"bytes,2,rep,name=groups,proto3" json:"groups,omitempty"`
	Namespace string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Roles are the role names bound to this caller here.
	Roles []string `protobuf:"bytes,4,rep,name=roles,proto3" json:"roles,omitempty"`
	// Allowed lists "verb kind" pairs this caller may do — enough for a
	// UI to hide what it must not offer.
	Allowed       []string `protobuf:"bytes,5,rep,name=allowed,proto3" json:"allowed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WhoAmIResponse) Reset() {
	*x = WhoAmIResponse{}
	mi := &file_proto_management_v1_rbac_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhoAmIResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhoAmIResponse) ProtoMessage() {}

func (x *WhoAmIResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_v1_rbac_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhoAmIResponse.ProtoReflect.Descriptor instead.
func (*WhoAmIResponse) Descriptor() ([]byte, []int) {
	return file_proto_management_v1_rbac_proto_rawDescGZIP(), []int{3}
}

func (x *WhoAmIResponse) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *WhoAmIResponse) GetGroups() []string {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *WhoAmIResponse) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *WhoAmIResponse) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *WhoAmIResponse) GetAllowed() []string {
	if x != nil {
		return x.Allowed
	}
	return nil
}

var File_proto_management_v1_rbac_proto protoreflect.FileDescriptor

const file_proto_management_v1_rbac_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/management/v1/rbac.proto\x12\x16graphene.management.v1\"_\n" +
	"\x12IssueTokenResponse\x12\x19\n" +
	"\btoken_id\x18\x01 \x01(\tR\atokenId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x18\n" +
	"\aexpires\x18\x03 \x01(\tR\aexpires\"h\n" +
	"\x11IssueTokenRequest\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12\x1f\n" +
	"\vttl_seconds\x18\x02 \x01(\x03R\n" +
	"ttlSeconds\x12\x18\n" +
	"\acomment\x18\x03 \x01(\tR\acomment\"\x0f\n" +
	"\rWhoAmIRequest\"\x90\x01\n" +
	"\x0eWhoAmIResponse\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x16\n" +
	"\x06groups\x18\x02 \x03(\tR\x06groups\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x14\n" +
	"\x05roles\x18\x04 \x03(\tR\x05roles\x12\x18\n" +
	"\aallowed\x18\x05 \x03(\tR\aallowed2\xc7\x01\n" +
	"\aRbacAPI\x12c\n" +
	"\n" +
	"IssueToken\x12).graphene.management.v1.IssueTokenRequest\x1a*.graphene.management.v1.IssueTokenResponse\x12W\n" +
	"\x06WhoAmI\x12%.graphene.management.v1.WhoAmIRequest\x1a&.graphene.management.v1.WhoAmIResponseBFZDgithub.com/graphene-ci/graphene/pkg/proto/management/v1;managementv1b\x06proto3"

var (
	file_proto_management_v1_rbac_proto_rawDescOnce sync.Once
	file_proto_management_v1_rbac_proto_rawDescData []byte
)

func file_proto_management_v1_rbac_proto_rawDescGZIP() []byte {
	file_proto_management_v1_rbac_proto_rawDescOnce.Do(func() {
		file_proto_management_v1_rbac_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_management_v1_rbac_proto_rawDesc), len(file_proto_management_v1_rbac_proto_rawDesc)))
	})
	return file_proto_management_v1_rbac_proto_rawDescData
}

var file_proto_management_v1_rbac_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_management_v1_rbac_proto_goTypes = []any{
	(*IssueTokenResponse)(nil), // 0: graphene.management.v1.IssueTokenResponse
	(*IssueTokenRequest)(nil),  // 1: graphene.management.v1.IssueTokenRequest
	(*WhoAmIRequest)(nil),      // 2: graphene.management.v1.WhoAmIRequest
	(*WhoAmIResponse)(nil),     // 3: graphene.management.v1.WhoAmIResponse
}
var file_proto_management_v1_rbac_proto_depIdxs = []int32{
	1, // 0: graphene.management.v1.RbacAPI.IssueToken:input_type -> graphene.management.v1.IssueTokenRequest
	2, // 1: graphene.management.v1.RbacAPI.WhoAmI:input_type -> graphene.management.v1.WhoAmIRequest
	0, // 2: graphene.management.v1.RbacAPI.IssueToken:output_type -> graphene.management.v1.IssueTokenResponse
	3, // 3: graphene.management.v1.RbacAPI.WhoAmI:output_type -> graphene.management.v1.WhoAmIResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_management_v1_rbac_proto_init() }
func file_proto_management_v1_rbac_proto_init() {
	if File_proto_management_v1_rbac_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_management_v1_rbac_proto_rawDesc), len(file_proto_management_v1_rbac_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_management_v1_rbac_proto_goTypes,
		DependencyIndexes: file_proto_management_v1_rbac_proto_depIdxs,
		MessageInfos:      file_proto_management_v1_rbac_proto_msgTypes,
	}.Build()
	File_proto_management_v1_rbac_proto = out.File
	file_proto_management_v1_rbac_proto_goTypes = nil
	file_proto_management_v1_rbac_proto_depIdxs = nil
}
