// Management plane: the business surface over resources — what a CLI,
// a UI, or graphene-ci-cloud drives. The caller's NAMESPACE comes from
// its token, never from a request: a foreign namespace cannot even be
// asked for.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: proto/management/v1/resources.proto

package managementv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Selector picks resources: every set field must match.
type Selector struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Kind of the record ("agent", "artifact", library kinds).
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// Phase: creating | ready | deleting | deleted | ...
	Phase string `protobuf:"bytes,2,opt,name=phase,proto3" json:"phase,omitempty"`
	// Owner ref ("run/x", "stand/p", "agent/vm-1").
	Owner string `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	// Labels matched by equality on the record's labels.
	Labels        map[string]string `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Selector) Reset() {
	*x = Selector{}
	mi := &file_proto_management_v1_resources_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Selector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Selector) ProtoMessage() {}

func (x *Selector) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_v1_resources_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Selector.ProtoReflect.Descriptor instead.
func (*Selector) Descriptor() ([]byte, []int) {
	return file_proto_management_v1_resources_proto_rawDescGZIP(), []int{0}
}

func (x *Selector) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Selector) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *Selector) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *Selector) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Selector      *Selector              `protobuf:"bytes,1,opt,name=selector,proto3" json:"selector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_proto_management_v1_resources_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_v1_resources_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_proto_management_v1_resources_proto_rawDescGZIP(), []int{1}
}

func (x *ListRequest) GetSelector() *Selector {
	if x != nil {
		return x.Selector
	}
	return nil
}

type Resource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Ref addresses the record: "kind/id" — also its workflow id.
	Ref   string `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	Kind  string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Phase string `protobuf:"bytes,3,opt,name=phase,proto3" json:"phase,omitempty"`
	// Owner is the CURRENT owner from the record's state.
	Owner string `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`
	// Spec and state as raw JSON — typed by whoever defined the kind.
	Spec              []byte `protobuf:"bytes,5,opt,name=spec,proto3" json:"spec,omitempty"`
	State             []byte `protobuf:"bytes,6,opt,name=state,proto3" json:"state,omitempty"`
	PendingCommands   int32  `protobuf:"varint,7,opt,name=pending_commands,json=pendingCommands,proto3" json:"pending_commands,omitempty"`
	MarkedForDeletion bool   `protobuf:"varint,8,opt,name=marked_for_deletion,json=markedForDeletion,proto3" json:"marked_for_deletion,omitempty"`
	// Labels are the record's markers — metric-label semantics; keys
	// under "graphene.io/" are written by the system.
	Labels        map[string]string `protobuf:"bytes,9,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_proto_management_v1_resources_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_v1_resources_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_proto_management_v1_resources_proto_rawDescGZIP(), []int{2}
}

func (x *Resource) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *Resource) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Resource) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *Resource) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *Resource) GetSpec() []byte {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *Resource) GetState() []byte {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *Resource) GetPendingCommands() int32 {
	if x != nil {
		return x.PendingCommands
	}
	return 0
}

func (x *Resource) GetMarkedForDeletion() bool {
	if x != nil {
		return x.MarkedForDeletion
	}
	return false
}

func (x *Resource) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resources     []*Resource            `protobuf:"bytes,1,rep,name=resources,proto3" json:"resources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_proto_management_v1_resources_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_v1_resources_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_proto_management_v1_resources_proto_rawDescGZIP(), []int{3}
}

func (x *ListResponse) GetResources() []*Resource {
	if x != nil {
		return x.Resources
	}
	return nil
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           string                 `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_proto_management_v1_resources_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_v1_resources_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_proto_management_v1_resources_proto_rawDescGZIP(), []int{4}
}

func (x *GetRequest) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      *Resource              `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_proto_management_v1_resources_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_v1_resources_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_proto_management_v1_resources_proto_rawDescGZIP(), []int{5}
}

func (x *GetResponse) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

type TreeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Owner to start from: "run/x", "stand/p", or a resource ref.
	Owner         string `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TreeRequest) Reset() {
	*x = TreeRequest{}
	mi := &file_proto_management_v1_resources_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TreeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TreeRequest) ProtoMessage() {}

func (x *TreeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_v1_resources_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TreeRequest.ProtoReflect.Descriptor instead.
func (*TreeRequest) Descriptor() ([]byte, []int) {
	return file_proto_management_v1_resources_proto_rawDescGZIP(), []int{6}
}

func (x *TreeRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

// TreeNode is one resource with its children.
type TreeNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      *Resource              `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Children      []*TreeNode            `protobuf:"bytes,2,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TreeNode) Reset() {
	*x = TreeNode{}
	mi := &file_proto_management_v1_resources_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TreeNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TreeNode) ProtoMessage() {}

func (x *TreeNode) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_v1_resources_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TreeNode.ProtoReflect.Descriptor instead.
func (*TreeNode) Descriptor() ([]byte, []int) {
	return file_proto_management_v1_resources_proto_rawDescGZIP(), []int{7}
}

func (x *TreeNode) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *TreeNode) GetChildren() []*TreeNode {
	if x != nil {
		return x.Children
	}
	return nil
}

type TreeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Roots         []*TreeNode            `protobuf:"bytes,1,rep,name=roots,proto3" json:"roots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TreeResponse) Reset() {
	*x = TreeResponse{}
	mi := &file_proto_management_v1_resources_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TreeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TreeResponse) ProtoMessage() {}

func (x *TreeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_v1_resources_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TreeResponse.ProtoReflect.Descriptor instead.
func (*TreeResponse) Descriptor() ([]byte, []int) {
	return file_proto_management_v1_resources_proto_rawDescGZIP(), []int{8}
}

func (x *TreeResponse) GetRoots() []*TreeNode {
	if x != nil {
		return x.Roots
	}
	return nil
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           string                 `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_proto_management_v1_resources_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_v1_resources_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_management_v1_resources_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteRequest) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_proto_management_v1_resources_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_v1_resources_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_proto_management_v1_resources_proto_rawDescGZIP(), []int{10}
}

type TransferRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Ref      string                 `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	NewOwner string                 `protobuf:"bytes,2,opt,name=new_owner,json=newOwner,proto3" json:"new_owner,omitempty"`
	// Keep bounds the stay under the new owner, seconds; 0 keeps the
	// resource until an explicit delete.
	KeepSeconds   int64 `protobuf:"varint,3,opt,name=keep_seconds,json=keepSeconds,proto3" json:"keep_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferRequest) Reset() {
	*x = TransferRequest{}
	mi := &file_proto_management_v1_resources_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferRequest) ProtoMessage() {}

func (x *TransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_v1_resources_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferRequest.ProtoReflect.Descriptor instead.
func (*TransferRequest) Descriptor() ([]byte, []int) {
	return file_proto_management_v1_resources_proto_rawDescGZIP(), []int{11}
}

func (x *TransferRequest) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *TransferRequest) GetNewOwner() string {
	if x != nil {
		return x.NewOwner
	}
	return ""
}

func (x *TransferRequest) GetKeepSeconds() int64 {
	if x != nil {
		return x.KeepSeconds
	}
	return 0
}

type TransferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferResponse) Reset() {
	*x = TransferResponse{}
	mi := &file_proto_management_v1_resources_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferResponse) ProtoMessage() {}

func (x *TransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_v1_resources_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferResponse.ProtoReflect.Descriptor instead.
func (*TransferResponse) Descriptor() ([]byte, []int) {
	return file_proto_management_v1_resources_proto_rawDescGZIP(), []int{12}
}

type InvokeRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Ref     string                 `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	Command string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	// Payload is the command's request as JSON.
	Payload []byte `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	// RequestId deduplicates retries (empty — generated).
	RequestId     string `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeRequest) Reset() {
	*x = InvokeRequest{}
	mi := &file_proto_management_v1_resources_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeRequest) ProtoMessage() {}

func (x *InvokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_v1_resources_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeRequest.ProtoReflect.Descriptor instead.
func (*InvokeRequest) Descriptor() ([]byte, []int) {
	return file_proto_management_v1_resources_proto_rawDescGZIP(), []int{13}
}

func (x *InvokeRequest) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *InvokeRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *InvokeRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *InvokeRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type InvokeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Result is the command's response as JSON.
	Result        []byte `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeResponse) Reset() {
	*x = InvokeResponse{}
	mi := &file_proto_management_v1_resources_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeResponse) ProtoMessage() {}

func (x *InvokeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_v1_resources_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeResponse.ProtoReflect.Descriptor instead.
func (*InvokeResponse) Descriptor() ([]byte, []int) {
	return file_proto_management_v1_resources_proto_rawDescGZIP(), []int{14}
}

func (x *InvokeResponse) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_proto_management_v1_resources_proto protoreflect.FileDescriptor

const file_proto_management_v1_resources_proto_rawDesc = "" +
	"\n" +
	"#proto/management/v1/resources.proto\x12\x16graphene.management.v1\"\xcb\x01\n" +
	"\bSelector\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x14\n" +
	"\x05phase\x18\x02 \x01(\tR\x05phase\x12\x14\n" +
	"\x05owner\x18\x03 \x01(\tR\x05owner\x12D\n" +
	"\x06labels\x18\x04 \x03(\v2,.graphene.management.v1.Selector.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"K\n" +
	"\vListRequest\x12<\n" +
	"\bselector\x18\x01 \x01(\v2 .graphene.management.v1.SelectorR\bselector\"\xe2\x02\n" +
	"\bResource\x12\x10\n" +
	"\x03ref\x18\x01 \x01(\tR\x03ref\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x14\n" +
	"\x05phase\x18\x03 \x01(\tR\x05phase\x12\x14\n" +
	"\x05owner\x18\x04 \x01(\tR\x05owner\x12\x12\n" +
	"\x04spec\x18\x05 \x01(\fR\x04spec\x12\x14\n" +
	"\x05state\x18\x06 \x01(\fR\x05state\x12)\n" +
	"\x10pending_commands\x18\a \x01(\x05R\x0fpendingCommands\x12.\n" +
	"\x13marked_for_deletion\x18\b \x01(\bR\x11markedForDeletion\x12D\n" +
	"\x06labels\x18\t \x03(\v2,.graphene.management.v1.Resource.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"N\n" +
	"\fListResponse\x12>\n" +
	"\tresources\x18\x01 \x03(\v2 .graphene.management.v1.ResourceR\tresources\"\x1e\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03ref\x18\x01 \x01(\tR\x03ref\"K\n" +
	"\vGetResponse\x12<\n" +
	"\bresource\x18\x01 \x01(\v2 .graphene.management.v1.ResourceR\bresource\"#\n" +
	"\vTreeRequest\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\"\x86\x01\n" +
	"\bTreeNode\x12<\n" +
	"\bresource\x18\x01 \x01(\v2 .graphene.management.v1.ResourceR\bresource\x12<\n" +
	"\bchildren\x18\x02 \x03(\v2 .graphene.management.v1.TreeNodeR\bchildren\"F\n" +
	"\fTreeResponse\x126\n" +
	"\x05roots\x18\x01 \x03(\v2 .graphene.management.v1.TreeNodeR\x05roots\"!\n" +
	"\rDeleteRequest\x12\x10\n" +
	"\x03ref\x18\x01 \x01(\tR\x03ref\"\x10\n" +
	"\x0eDeleteResponse\"c\n" +
	"\x0fTransferRequest\x12\x10\n" +
	"\x03ref\x18\x01 \x01(\tR\x03ref\x12\x1b\n" +
	"\tnew_owner\x18\x02 \x01(\tR\bnewOwner\x12!\n" +
	"\fkeep_seconds\x18\x03 \x01(\x03R\vkeepSeconds\"\x12\n" +
	"\x10TransferResponse\"t\n" +
	"\rInvokeRequest\x12\x10\n" +
	"\x03ref\x18\x01 \x01(\tR\x03ref\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\"(\n" +
	"\x0eInvokeResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\fR\x06result2\x95\x04\n" +
	"\fResourcesAPI\x12Q\n" +
	"\x04List\x12#.graphene.management.v1.ListRequest\x1a$.graphene.management.v1.ListResponse\x12N\n" +
	"\x03Get\x12\".graphene.management.v1.GetRequest\x1a#.graphene.management.v1.GetResponse\x12Q\n" +
	"\x04Tree\x12#.graphene.management.v1.TreeRequest\x1a$.graphene.management.v1.TreeResponse\x12W\n" +
	"\x06Delete\x12%.graphene.management.v1.DeleteRequest\x1a&.graphene.management.v1.DeleteResponse\x12]\n" +
	"\bTransfer\x12'.graphene.management.v1.TransferRequest\x1a(.graphene.management.v1.TransferResponse\x12W\n" +
	"\x06Invoke\x12%.graphene.management.v1.InvokeRequest\x1a&.graphene.management.v1.InvokeResponseBFZDgithub.com/graphene-ci/graphene/pkg/proto/management/v1;managementv1b\x06proto3"

var (
	file_proto_management_v1_resources_proto_rawDescOnce sync.Once
	file_proto_management_v1_resources_proto_rawDescData []byte
)

func file_proto_management_v1_resources_proto_rawDescGZIP() []byte {
	file_proto_management_v1_resources_proto_rawDescOnce.Do(func() {
		file_proto_management_v1_resources_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_management_v1_resources_proto_rawDesc), len(file_proto_management_v1_resources_proto_rawDesc)))
	})
	return file_proto_management_v1_resources_proto_rawDescData
}

var file_proto_management_v1_resources_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_management_v1_resources_proto_goTypes = []any{
	(*Selector)(nil),         // 0: graphene.management.v1.Selector
	(*ListRequest)(nil),      // 1: graphene.management.v1.ListRequest
	(*Resource)(nil),         // 2: graphene.management.v1.Resource
	(*ListResponse)(nil),     // 3: graphene.management.v1.ListResponse
	(*GetRequest)(nil),       // 4: graphene.management.v1.GetRequest
	(*GetResponse)(nil),      // 5: graphene.management.v1.GetResponse
	(*TreeRequest)(nil),      // 6: graphene.management.v1.TreeRequest
	(*TreeNode)(nil),         // 7: graphene.management.v1.TreeNode
	(*TreeResponse)(nil),     // 8: graphene.management.v1.TreeResponse
	(*DeleteRequest)(nil),    // 9: graphene.management.v1.DeleteRequest
	(*DeleteResponse)(nil),   // 10: graphene.management.v1.DeleteResponse
	(*TransferRequest)(nil),  // 11: graphene.management.v1.TransferRequest
	(*TransferResponse)(nil), // 12: graphene.management.v1.TransferResponse
	(*InvokeRequest)(nil),    // 13: graphene.management.v1.InvokeRequest
	(*InvokeResponse)(nil),   // 14: graphene.management.v1.InvokeResponse
	nil,                      // 15: graphene.management.v1.Selector.LabelsEntry
	nil,                      // 16: graphene.management.v1.Resource.LabelsEntry
}
var file_proto_management_v1_resources_proto_depIdxs = []int32{
	15, // 0: graphene.management.v1.Selector.labels:type_name -> graphene.management.v1.Selector.LabelsEntry
	0,  // 1: graphene.management.v1.ListRequest.selector:type_name -> graphene.management.v1.Selector
	16, // 2: graphene.management.v1.Resource.labels:type_name -> graphene.management.v1.Resource.LabelsEntry
	2,  // 3: graphene.management.v1.ListResponse.resources:type_name -> graphene.management.v1.Resource
	2,  // 4: graphene.management.v1.GetResponse.resource:type_name -> graphene.management.v1.Resource
	2,  // 5: graphene.management.v1.TreeNode.resource:type_name -> graphene.management.v1.Resource
	7,  // 6: graphene.management.v1.TreeNode.children:type_name -> graphene.management.v1.TreeNode
	7,  // 7: graphene.management.v1.TreeResponse.roots:type_name -> graphene.management.v1.TreeNode
	1,  // 8: graphene.management.v1.ResourcesAPI.List:input_type -> graphene.management.v1.ListRequest
	4,  // 9: graphene.management.v1.ResourcesAPI.Get:input_type -> graphene.management.v1.GetRequest
	6,  // 10: graphene.management.v1.ResourcesAPI.Tree:input_type -> graphene.management.v1.TreeRequest
	9,  // 11: graphene.management.v1.ResourcesAPI.Delete:input_type -> graphene.management.v1.DeleteRequest
	11, // 12: graphene.management.v1.ResourcesAPI.Transfer:input_type -> graphene.management.v1.TransferRequest
	13, // 13: graphene.management.v1.ResourcesAPI.Invoke:input_type -> graphene.management.v1.InvokeRequest
	3,  // 14: graphene.management.v1.ResourcesAPI.List:output_type -> graphene.management.v1.ListResponse
	5,  // 15: graphene.management.v1.ResourcesAPI.Get:output_type -> graphene.management.v1.GetResponse
	8,  // 16: graphene.management.v1.ResourcesAPI.Tree:output_type -> graphene.management.v1.TreeResponse
	10, // 17: graphene.management.v1.ResourcesAPI.Delete:output_type -> graphene.management.v1.DeleteResponse
	12, // 18: graphene.management.v1.ResourcesAPI.Transfer:output_type -> graphene.management.v1.TransferResponse
	14, // 19: graphene.management.v1.ResourcesAPI.Invoke:output_type -> graphene.management.v1.InvokeResponse
	14, // [14:20] is the sub-list for method output_type
	8,  // [8:14] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_management_v1_resources_proto_init() }
func file_proto_management_v1_resources_proto_init() {
	if File_proto_management_v1_resources_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_management_v1_resources_proto_rawDesc), len(file_proto_management_v1_resources_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_management_v1_resources_proto_goTypes,
		DependencyIndexes: file_proto_management_v1_resources_proto_depIdxs,
		MessageInfos:      file_proto_management_v1_resources_proto_msgTypes,
	}.Build()
	File_proto_management_v1_resources_proto = out.File
	file_proto_management_v1_resources_proto_goTypes = nil
	file_proto_management_v1_resources_proto_depIdxs = nil
}
