// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: proto/management/v1/revisions.proto

package managementv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RevisionsAPI_Materialize_FullMethodName      = "/graphene.management.v1.RevisionsAPI/Materialize"
	RevisionsAPI_ListRevisions_FullMethodName    = "/graphene.management.v1.RevisionsAPI/ListRevisions"
	RevisionsAPI_RunRevision_FullMethodName      = "/graphene.management.v1.RevisionsAPI/RunRevision"
	RevisionsAPI_ActivateRevision_FullMethodName = "/graphene.management.v1.RevisionsAPI/ActivateRevision"
)

// RevisionsAPIClient is the client API for RevisionsAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RevisionsAPI is the source-first contour: a SOURCE TREE goes in, the
// server materializes it (build in a runtime container, manifest from
// the binary's describe mode, ko-style OCI push), and the result is a
// PIPELINE REVISION — runnable as a draft, activatable as the version
// automatic starts use. No user-side push exists on this path.
type RevisionsAPIClient interface {
	// Materialize STREAMS progress: a source build takes minutes, and a
	// silent request dies on the first idle NAT between the client and
	// the door. The stream is also the Studio build log.
	Materialize(ctx context.Context, in *MaterializeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MaterializeEvent], error)
	ListRevisions(ctx context.Context, in *ListRevisionsRequest, opts ...grpc.CallOption) (*ListRevisionsResponse, error)
	RunRevision(ctx context.Context, in *RunRevisionRequest, opts ...grpc.CallOption) (*RunRevisionResponse, error)
	ActivateRevision(ctx context.Context, in *ActivateRevisionRequest, opts ...grpc.CallOption) (*ActivateRevisionResponse, error)
}

type revisionsAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewRevisionsAPIClient(cc grpc.ClientConnInterface) RevisionsAPIClient {
	return &revisionsAPIClient{cc}
}

func (c *revisionsAPIClient) Materialize(ctx context.Context, in *MaterializeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MaterializeEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RevisionsAPI_ServiceDesc.Streams[0], RevisionsAPI_Materialize_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[MaterializeRequest, MaterializeEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RevisionsAPI_MaterializeClient = grpc.ServerStreamingClient[MaterializeEvent]

func (c *revisionsAPIClient) ListRevisions(ctx context.Context, in *ListRevisionsRequest, opts ...grpc.CallOption) (*ListRevisionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRevisionsResponse)
	err := c.cc.Invoke(ctx, RevisionsAPI_ListRevisions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *revisionsAPIClient) RunRevision(ctx context.Context, in *RunRevisionRequest, opts ...grpc.CallOption) (*RunRevisionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunRevisionResponse)
	err := c.cc.Invoke(ctx, RevisionsAPI_RunRevision_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *revisionsAPIClient) ActivateRevision(ctx context.Context, in *ActivateRevisionRequest, opts ...grpc.CallOption) (*ActivateRevisionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActivateRevisionResponse)
	err := c.cc.Invoke(ctx, RevisionsAPI_ActivateRevision_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RevisionsAPIServer is the server API for RevisionsAPI service.
// All implementations must embed UnimplementedRevisionsAPIServer
// for forward compatibility.
//
// RevisionsAPI is the source-first contour: a SOURCE TREE goes in, the
// server materializes it (build in a runtime container, manifest from
// the binary's describe mode, ko-style OCI push), and the result is a
// PIPELINE REVISION — runnable as a draft, activatable as the version
// automatic starts use. No user-side push exists on this path.
type RevisionsAPIServer interface {
	// Materialize STREAMS progress: a source build takes minutes, and a
	// silent request dies on the first idle NAT between the client and
	// the door. The stream is also the Studio build log.
	Materialize(*MaterializeRequest, grpc.ServerStreamingServer[MaterializeEvent]) error
	ListRevisions(context.Context, *ListRevisionsRequest) (*ListRevisionsResponse, error)
	RunRevision(context.Context, *RunRevisionRequest) (*RunRevisionResponse, error)
	ActivateRevision(context.Context, *ActivateRevisionRequest) (*ActivateRevisionResponse, error)
	mustEmbedUnimplementedRevisionsAPIServer()
}

// UnimplementedRevisionsAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRevisionsAPIServer struct{}

func (UnimplementedRevisionsAPIServer) Materialize(*MaterializeRequest, grpc.ServerStreamingServer[MaterializeEvent]) error {
	return status.Error(codes.Unimplemented, "method Materialize not implemented")
}
func (UnimplementedRevisionsAPIServer) ListRevisions(context.Context, *ListRevisionsRequest) (*ListRevisionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRevisions not implemented")
}
func (UnimplementedRevisionsAPIServer) RunRevision(context.Context, *RunRevisionRequest) (*RunRevisionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunRevision not implemented")
}
func (UnimplementedRevisionsAPIServer) ActivateRevision(context.Context, *ActivateRevisionRequest) (*ActivateRevisionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ActivateRevision not implemented")
}
func (UnimplementedRevisionsAPIServer) mustEmbedUnimplementedRevisionsAPIServer() {}
func (UnimplementedRevisionsAPIServer) testEmbeddedByValue()                      {}

// UnsafeRevisionsAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RevisionsAPIServer will
// result in compilation errors.
type UnsafeRevisionsAPIServer interface {
	mustEmbedUnimplementedRevisionsAPIServer()
}

func RegisterRevisionsAPIServer(s grpc.ServiceRegistrar, srv RevisionsAPIServer) {
	// If the following call panics, it indicates UnimplementedRevisionsAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RevisionsAPI_ServiceDesc, srv)
}

func _RevisionsAPI_Materialize_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(MaterializeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RevisionsAPIServer).Materialize(m, &grpc.GenericServerStream[MaterializeRequest, MaterializeEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RevisionsAPI_MaterializeServer = grpc.ServerStreamingServer[MaterializeEvent]

func _RevisionsAPI_ListRevisions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRevisionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RevisionsAPIServer).ListRevisions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RevisionsAPI_ListRevisions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RevisionsAPIServer).ListRevisions(ctx, req.(*ListRevisionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RevisionsAPI_RunRevision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunRevisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RevisionsAPIServer).RunRevision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RevisionsAPI_RunRevision_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RevisionsAPIServer).RunRevision(ctx, req.(*RunRevisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RevisionsAPI_ActivateRevision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivateRevisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RevisionsAPIServer).ActivateRevision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RevisionsAPI_ActivateRevision_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RevisionsAPIServer).ActivateRevision(ctx, req.(*ActivateRevisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RevisionsAPI_ServiceDesc is the grpc.ServiceDesc for RevisionsAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RevisionsAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "graphene.management.v1.RevisionsAPI",
	HandlerType: (*RevisionsAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListRevisions",
			Handler:    _RevisionsAPI_ListRevisions_Handler,
		},
		{
			MethodName: "RunRevision",
			Handler:    _RevisionsAPI_RunRevision_Handler,
		},
		{
			MethodName: "ActivateRevision",
			Handler:    _RevisionsAPI_ActivateRevision_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Materialize",
			Handler:       _RevisionsAPI_Materialize_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/management/v1/revisions.proto",
}
