// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: proto/management/v1/revisions.proto

package managementv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MaterializeRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	PipelineId string                 `protobuf:"bytes,1,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	// The full source tree as tar.gz — the tree root is the build root:
	// `go build .`, one package main. Empty builds the PIPELINE's own
	// working tree, which already lives on the server.
	Source        []byte `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MaterializeRequest) Reset() {
	*x = MaterializeRequest{}
	mi := &file_proto_management_v1_revisions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaterializeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaterializeRequest) ProtoMessage() {}

func (x *MaterializeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_v1_revisions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaterializeRequest.ProtoReflect.Descriptor instead.
func (*MaterializeRequest) Descriptor() ([]byte, []int) {
	return file_proto_management_v1_revisions_proto_rawDescGZIP(), []int{0}
}

func (x *MaterializeRequest) GetPipelineId() string {
	if x != nil {
		return x.PipelineId
	}
	return ""
}

func (x *MaterializeRequest) GetSource() []byte {
	if x != nil {
		return x.Source
	}
	return nil
}

type MaterializeEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stage: "upload" | "runtime" | "build" | "describe" | "publish" |
	// "done" — the phase this event reports.
	Stage string `protobuf:"bytes,1,opt,name=stage,proto3" json:"stage,omitempty"`
	// Message is one progress line (a build log line, a status).
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Result is set on the final "done" event.
	Result        *MaterializeResult `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MaterializeEvent) Reset() {
	*x = MaterializeEvent{}
	mi := &file_proto_management_v1_revisions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaterializeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaterializeEvent) ProtoMessage() {}

func (x *MaterializeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_v1_revisions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaterializeEvent.ProtoReflect.Descriptor instead.
func (*MaterializeEvent) Descriptor() ([]byte, []int) {
	return file_proto_management_v1_revisions_proto_rawDescGZIP(), []int{1}
}

func (x *MaterializeEvent) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *MaterializeEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MaterializeEvent) GetResult() *MaterializeResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type MaterializeResult struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	RevisionId string                 `protobuf:"bytes,1,opt,name=revision_id,json=revisionId,proto3" json:"revision_id,omitempty"`
	Image      string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	// The revision's manifest as protojson — what Plan renders.
	Manifest      []byte `protobuf:"bytes,3,opt,name=manifest,proto3" json:"manifest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MaterializeResult) Reset() {
	*x = MaterializeResult{}
	mi := &file_proto_management_v1_revisions_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaterializeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaterializeResult) ProtoMessage() {}

func (x *MaterializeResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_v1_revisions_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaterializeResult.ProtoReflect.Descriptor instead.
func (*MaterializeResult) Descriptor() ([]byte, []int) {
	return file_proto_management_v1_revisions_proto_rawDescGZIP(), []int{2}
}

func (x *MaterializeResult) GetRevisionId() string {
	if x != nil {
		return x.RevisionId
	}
	return ""
}

func (x *MaterializeResult) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *MaterializeResult) GetManifest() []byte {
	if x != nil {
		return x.Manifest
	}
	return nil
}

type RunRevisionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PipelineId    string                 `protobuf:"bytes,1,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	RevisionId    string                 `protobuf:"bytes,2,opt,name=revision_id,json=revisionId,proto3" json:"revision_id,omitempty"`
	RunId         string                 `protobuf:"bytes,3,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Params        []byte                 `protobuf:"bytes,4,opt,name=params,proto3" json:"params,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunRevisionRequest) Reset() {
	*x = RunRevisionRequest{}
	mi := &file_proto_management_v1_revisions_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunRevisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunRevisionRequest) ProtoMessage() {}

func (x *RunRevisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_v1_revisions_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunRevisionRequest.ProtoReflect.Descriptor instead.
func (*RunRevisionRequest) Descriptor() ([]byte, []int) {
	return file_proto_management_v1_revisions_proto_rawDescGZIP(), []int{3}
}

func (x *RunRevisionRequest) GetPipelineId() string {
	if x != nil {
		return x.PipelineId
	}
	return ""
}

func (x *RunRevisionRequest) GetRevisionId() string {
	if x != nil {
		return x.RevisionId
	}
	return ""
}

func (x *RunRevisionRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *RunRevisionRequest) GetParams() []byte {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *RunRevisionRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type RunRevisionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	TemporalRunId string                 `protobuf:"bytes,2,opt,name=temporal_run_id,json=temporalRunId,proto3" json:"temporal_run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunRevisionResponse) Reset() {
	*x = RunRevisionResponse{}
	mi := &file_proto_management_v1_revisions_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunRevisionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunRevisionResponse) ProtoMessage() {}

func (x *RunRevisionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_v1_revisions_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunRevisionResponse.ProtoReflect.Descriptor instead.
func (*RunRevisionResponse) Descriptor() ([]byte, []int) {
	return file_proto_management_v1_revisions_proto_rawDescGZIP(), []int{4}
}

func (x *RunRevisionResponse) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *RunRevisionResponse) GetTemporalRunId() string {
	if x != nil {
		return x.TemporalRunId
	}
	return ""
}

var File_proto_management_v1_revisions_proto protoreflect.FileDescriptor

const file_proto_management_v1_revisions_proto_rawDesc = "" +
	"\n" +
	"#proto/management/v1/revisions.proto\x12\x16graphene.management.v1\"M\n" +
	"\x12MaterializeRequest\x12\x1f\n" +
	"\vpipeline_id\x18\x01 \x01(\tR\n" +
	"pipelineId\x12\x16\n" +
	"\x06source\x18\x02 \x01(\fR\x06source\"\x85\x01\n" +
	"\x10MaterializeEvent\x12\x14\n" +
	"\x05stage\x18\x01 \x01(\tR\x05stage\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12A\n" +
	"\x06result\x18\x03 \x01(\v2).graphene.management.v1.MaterializeResultR\x06result\"f\n" +
	"\x11MaterializeResult\x12\x1f\n" +
	"\vrevision_id\x18\x01 \x01(\tR\n" +
	"revisionId\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x12\x1a\n" +
	"\bmanifest\x18\x03 \x01(\fR\bmanifest\"\x90\x02\n" +
	"\x12RunRevisionRequest\x12\x1f\n" +
	"\vpipeline_id\x18\x01 \x01(\tR\n" +
	"pipelineId\x12\x1f\n" +
	"\vrevision_id\x18\x02 \x01(\tR\n" +
	"revisionId\x12\x15\n" +
	"\x06run_id\x18\x03 \x01(\tR\x05runId\x12\x16\n" +
	"\x06params\x18\x04 \x01(\fR\x06params\x12N\n" +
	"\x06labels\x18\x05 \x03(\v26.graphene.management.v1.RunRevisionRequest.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"^\n" +
	"\x13RunRevisionResponse\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x12&\n" +
	"\x0ftemporal_run_id\x18\x02 \x01(\tR\rtemporalRunId2\xdd\x01\n" +
	"\fRevisionsAPI\x12e\n" +
	"\vMaterialize\x12*.graphene.management.v1.MaterializeRequest\x1a(.graphene.management.v1.MaterializeEvent0\x01\x12f\n" +
	"\vRunRevision\x12*.graphene.management.v1.RunRevisionRequest\x1a+.graphene.management.v1.RunRevisionResponseBFZDgithub.com/graphene-ci/graphene/pkg/proto/management/v1;managementv1b\x06proto3"

var (
	file_proto_management_v1_revisions_proto_rawDescOnce sync.Once
	file_proto_management_v1_revisions_proto_rawDescData []byte
)

func file_proto_management_v1_revisions_proto_rawDescGZIP() []byte {
	file_proto_management_v1_revisions_proto_rawDescOnce.Do(func() {
		file_proto_management_v1_revisions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_management_v1_revisions_proto_rawDesc), len(file_proto_management_v1_revisions_proto_rawDesc)))
	})
	return file_proto_management_v1_revisions_proto_rawDescData
}

var file_proto_management_v1_revisions_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_management_v1_revisions_proto_goTypes = []any{
	(*MaterializeRequest)(nil),  // 0: graphene.management.v1.MaterializeRequest
	(*MaterializeEvent)(nil),    // 1: graphene.management.v1.MaterializeEvent
	(*MaterializeResult)(nil),   // 2: graphene.management.v1.MaterializeResult
	(*RunRevisionRequest)(nil),  // 3: graphene.management.v1.RunRevisionRequest
	(*RunRevisionResponse)(nil), // 4: graphene.management.v1.RunRevisionResponse
	nil,                         // 5: graphene.management.v1.RunRevisionRequest.LabelsEntry
}
var file_proto_management_v1_revisions_proto_depIdxs = []int32{
	2, // 0: graphene.management.v1.MaterializeEvent.result:type_name -> graphene.management.v1.MaterializeResult
	5, // 1: graphene.management.v1.RunRevisionRequest.labels:type_name -> graphene.management.v1.RunRevisionRequest.LabelsEntry
	0, // 2: graphene.management.v1.RevisionsAPI.Materialize:input_type -> graphene.management.v1.MaterializeRequest
	3, // 3: graphene.management.v1.RevisionsAPI.RunRevision:input_type -> graphene.management.v1.RunRevisionRequest
	1, // 4: graphene.management.v1.RevisionsAPI.Materialize:output_type -> graphene.management.v1.MaterializeEvent
	4, // 5: graphene.management.v1.RevisionsAPI.RunRevision:output_type -> graphene.management.v1.RunRevisionResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_management_v1_revisions_proto_init() }
func file_proto_management_v1_revisions_proto_init() {
	if File_proto_management_v1_revisions_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_management_v1_revisions_proto_rawDesc), len(file_proto_management_v1_revisions_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_management_v1_revisions_proto_goTypes,
		DependencyIndexes: file_proto_management_v1_revisions_proto_depIdxs,
		MessageInfos:      file_proto_management_v1_revisions_proto_msgTypes,
	}.Build()
	File_proto_management_v1_revisions_proto = out.File
	file_proto_management_v1_revisions_proto_goTypes = nil
	file_proto_management_v1_revisions_proto_depIdxs = nil
}
