// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: proto/management/v1/runs.proto

package managementv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RunsAPI_StartRun_FullMethodName  = "/graphene.management.v1.RunsAPI/StartRun"
	RunsAPI_GetRun_FullMethodName    = "/graphene.management.v1.RunsAPI/GetRun"
	RunsAPI_WatchRun_FullMethodName  = "/graphene.management.v1.RunsAPI/WatchRun"
	RunsAPI_RunResult_FullMethodName = "/graphene.management.v1.RunsAPI/RunResult"
	RunsAPI_CancelRun_FullMethodName = "/graphene.management.v1.RunsAPI/CancelRun"
)

// RunsAPIClient is the client API for RunsAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RunsAPI starts and observes pipeline runs. The worker — a managed
// container or an inplace binary — serves the run's queue; the server
// starts the workflow (and the container, when the run is managed).
type RunsAPIClient interface {
	StartRun(ctx context.Context, in *StartRunRequest, opts ...grpc.CallOption) (*StartRunResponse, error)
	GetRun(ctx context.Context, in *GetRunRequest, opts ...grpc.CallOption) (*GetRunResponse, error)
	// WatchRun streams the run's status transitions until a terminal
	// one; the first message carries the current status immediately.
	WatchRun(ctx context.Context, in *WatchRunRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchRunEvent], error)
	// Result waits for the run to finish and returns its typed result as
	// JSON.
	RunResult(ctx context.Context, in *RunResultRequest, opts ...grpc.CallOption) (*RunResultResponse, error)
	// Cancel asks the run to stop; the guaranteed-teardown path still
	// runs (unlike a terminate).
	// Listing lives in ResourcesAPI.List under the system kind "run" —
	// this service is the VERBS of a run's lifecycle only.
	CancelRun(ctx context.Context, in *CancelRunRequest, opts ...grpc.CallOption) (*CancelRunResponse, error)
}

type runsAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewRunsAPIClient(cc grpc.ClientConnInterface) RunsAPIClient {
	return &runsAPIClient{cc}
}

func (c *runsAPIClient) StartRun(ctx context.Context, in *StartRunRequest, opts ...grpc.CallOption) (*StartRunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartRunResponse)
	err := c.cc.Invoke(ctx, RunsAPI_StartRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runsAPIClient) GetRun(ctx context.Context, in *GetRunRequest, opts ...grpc.CallOption) (*GetRunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRunResponse)
	err := c.cc.Invoke(ctx, RunsAPI_GetRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runsAPIClient) WatchRun(ctx context.Context, in *WatchRunRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchRunEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RunsAPI_ServiceDesc.Streams[0], RunsAPI_WatchRun_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchRunRequest, WatchRunEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RunsAPI_WatchRunClient = grpc.ServerStreamingClient[WatchRunEvent]

func (c *runsAPIClient) RunResult(ctx context.Context, in *RunResultRequest, opts ...grpc.CallOption) (*RunResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunResultResponse)
	err := c.cc.Invoke(ctx, RunsAPI_RunResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runsAPIClient) CancelRun(ctx context.Context, in *CancelRunRequest, opts ...grpc.CallOption) (*CancelRunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelRunResponse)
	err := c.cc.Invoke(ctx, RunsAPI_CancelRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RunsAPIServer is the server API for RunsAPI service.
// All implementations must embed UnimplementedRunsAPIServer
// for forward compatibility.
//
// RunsAPI starts and observes pipeline runs. The worker — a managed
// container or an inplace binary — serves the run's queue; the server
// starts the workflow (and the container, when the run is managed).
type RunsAPIServer interface {
	StartRun(context.Context, *StartRunRequest) (*StartRunResponse, error)
	GetRun(context.Context, *GetRunRequest) (*GetRunResponse, error)
	// WatchRun streams the run's status transitions until a terminal
	// one; the first message carries the current status immediately.
	WatchRun(*WatchRunRequest, grpc.ServerStreamingServer[WatchRunEvent]) error
	// Result waits for the run to finish and returns its typed result as
	// JSON.
	RunResult(context.Context, *RunResultRequest) (*RunResultResponse, error)
	// Cancel asks the run to stop; the guaranteed-teardown path still
	// runs (unlike a terminate).
	// Listing lives in ResourcesAPI.List under the system kind "run" —
	// this service is the VERBS of a run's lifecycle only.
	CancelRun(context.Context, *CancelRunRequest) (*CancelRunResponse, error)
	mustEmbedUnimplementedRunsAPIServer()
}

// UnimplementedRunsAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRunsAPIServer struct{}

func (UnimplementedRunsAPIServer) StartRun(context.Context, *StartRunRequest) (*StartRunResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartRun not implemented")
}
func (UnimplementedRunsAPIServer) GetRun(context.Context, *GetRunRequest) (*GetRunResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRun not implemented")
}
func (UnimplementedRunsAPIServer) WatchRun(*WatchRunRequest, grpc.ServerStreamingServer[WatchRunEvent]) error {
	return status.Error(codes.Unimplemented, "method WatchRun not implemented")
}
func (UnimplementedRunsAPIServer) RunResult(context.Context, *RunResultRequest) (*RunResultResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunResult not implemented")
}
func (UnimplementedRunsAPIServer) CancelRun(context.Context, *CancelRunRequest) (*CancelRunResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelRun not implemented")
}
func (UnimplementedRunsAPIServer) mustEmbedUnimplementedRunsAPIServer() {}
func (UnimplementedRunsAPIServer) testEmbeddedByValue()                 {}

// UnsafeRunsAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RunsAPIServer will
// result in compilation errors.
type UnsafeRunsAPIServer interface {
	mustEmbedUnimplementedRunsAPIServer()
}

func RegisterRunsAPIServer(s grpc.ServiceRegistrar, srv RunsAPIServer) {
	// If the following call panics, it indicates UnimplementedRunsAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RunsAPI_ServiceDesc, srv)
}

func _RunsAPI_StartRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunsAPIServer).StartRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunsAPI_StartRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunsAPIServer).StartRun(ctx, req.(*StartRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunsAPI_GetRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunsAPIServer).GetRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunsAPI_GetRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunsAPIServer).GetRun(ctx, req.(*GetRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunsAPI_WatchRun_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchRunRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RunsAPIServer).WatchRun(m, &grpc.GenericServerStream[WatchRunRequest, WatchRunEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RunsAPI_WatchRunServer = grpc.ServerStreamingServer[WatchRunEvent]

func _RunsAPI_RunResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunsAPIServer).RunResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunsAPI_RunResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunsAPIServer).RunResult(ctx, req.(*RunResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunsAPI_CancelRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunsAPIServer).CancelRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunsAPI_CancelRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunsAPIServer).CancelRun(ctx, req.(*CancelRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RunsAPI_ServiceDesc is the grpc.ServiceDesc for RunsAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RunsAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "graphene.management.v1.RunsAPI",
	HandlerType: (*RunsAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartRun",
			Handler:    _RunsAPI_StartRun_Handler,
		},
		{
			MethodName: "GetRun",
			Handler:    _RunsAPI_GetRun_Handler,
		},
		{
			MethodName: "RunResult",
			Handler:    _RunsAPI_RunResult_Handler,
		},
		{
			MethodName: "CancelRun",
			Handler:    _RunsAPI_CancelRun_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchRun",
			Handler:       _RunsAPI_WatchRun_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/management/v1/runs.proto",
}
