// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: proto/management/v1/secrets.proto

package managementv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SecretsAPI_SetSecret_FullMethodName = "/graphene.management.v1.SecretsAPI/SetSecret"
)

// SecretsAPIClient is the client API for SecretsAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SecretsAPI is the one channel a secret VALUE travels: in, once, and
// never back. Everything else about a secret — that the name exists,
// who owns it, when it was last rotated, deleting it — is the ordinary
// record of kind "secret", read and written through ResourcesAPI. The
// value cannot ride a record's command: a command payload becomes a
// history event, and a history is forever.
type SecretsAPIClient interface {
	SetSecret(ctx context.Context, in *SetSecretRequest, opts ...grpc.CallOption) (*SetSecretResponse, error)
}

type secretsAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewSecretsAPIClient(cc grpc.ClientConnInterface) SecretsAPIClient {
	return &secretsAPIClient{cc}
}

func (c *secretsAPIClient) SetSecret(ctx context.Context, in *SetSecretRequest, opts ...grpc.CallOption) (*SetSecretResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetSecretResponse)
	err := c.cc.Invoke(ctx, SecretsAPI_SetSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SecretsAPIServer is the server API for SecretsAPI service.
// All implementations must embed UnimplementedSecretsAPIServer
// for forward compatibility.
//
// SecretsAPI is the one channel a secret VALUE travels: in, once, and
// never back. Everything else about a secret — that the name exists,
// who owns it, when it was last rotated, deleting it — is the ordinary
// record of kind "secret", read and written through ResourcesAPI. The
// value cannot ride a record's command: a command payload becomes a
// history event, and a history is forever.
type SecretsAPIServer interface {
	SetSecret(context.Context, *SetSecretRequest) (*SetSecretResponse, error)
	mustEmbedUnimplementedSecretsAPIServer()
}

// UnimplementedSecretsAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSecretsAPIServer struct{}

func (UnimplementedSecretsAPIServer) SetSecret(context.Context, *SetSecretRequest) (*SetSecretResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetSecret not implemented")
}
func (UnimplementedSecretsAPIServer) mustEmbedUnimplementedSecretsAPIServer() {}
func (UnimplementedSecretsAPIServer) testEmbeddedByValue()                    {}

// UnsafeSecretsAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SecretsAPIServer will
// result in compilation errors.
type UnsafeSecretsAPIServer interface {
	mustEmbedUnimplementedSecretsAPIServer()
}

func RegisterSecretsAPIServer(s grpc.ServiceRegistrar, srv SecretsAPIServer) {
	// If the following call panics, it indicates UnimplementedSecretsAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SecretsAPI_ServiceDesc, srv)
}

func _SecretsAPI_SetSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecretsAPIServer).SetSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecretsAPI_SetSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecretsAPIServer).SetSecret(ctx, req.(*SetSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SecretsAPI_ServiceDesc is the grpc.ServiceDesc for SecretsAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SecretsAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "graphene.management.v1.SecretsAPI",
	HandlerType: (*SecretsAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetSecret",
			Handler:    _SecretsAPI_SetSecret_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/management/v1/secrets.proto",
}
