// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: proto/management/v1/secrets.proto

package managementv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSecretRequest) Reset() {
	*x = SetSecretRequest{}
	mi := &file_proto_management_v1_secrets_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSecretRequest) ProtoMessage() {}

func (x *SetSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_v1_secrets_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSecretRequest.ProtoReflect.Descriptor instead.
func (*SetSecretRequest) Descriptor() ([]byte, []int) {
	return file_proto_management_v1_secrets_proto_rawDescGZIP(), []int{0}
}

func (x *SetSecretRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SetSecretRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SetSecretResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Version is what the record now counts: how many times this name
	// has been written.
	Version       int32 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSecretResponse) Reset() {
	*x = SetSecretResponse{}
	mi := &file_proto_management_v1_secrets_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSecretResponse) ProtoMessage() {}

func (x *SetSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_v1_secrets_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSecretResponse.ProtoReflect.Descriptor instead.
func (*SetSecretResponse) Descriptor() ([]byte, []int) {
	return file_proto_management_v1_secrets_proto_rawDescGZIP(), []int{1}
}

func (x *SetSecretResponse) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

var File_proto_management_v1_secrets_proto protoreflect.FileDescriptor

const file_proto_management_v1_secrets_proto_rawDesc = "" +
	"\n" +
	"!proto/management/v1/secrets.proto\x12\x16graphene.management.v1\"<\n" +
	"\x10SetSecretRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"-\n" +
	"\x11SetSecretResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x05R\aversion2n\n" +
	"\n" +
	"SecretsAPI\x12`\n" +
	"\tSetSecret\x12(.graphene.management.v1.SetSecretRequest\x1a).graphene.management.v1.SetSecretResponseBFZDgithub.com/graphene-ci/graphene/pkg/proto/management/v1;managementv1b\x06proto3"

var (
	file_proto_management_v1_secrets_proto_rawDescOnce sync.Once
	file_proto_management_v1_secrets_proto_rawDescData []byte
)

func file_proto_management_v1_secrets_proto_rawDescGZIP() []byte {
	file_proto_management_v1_secrets_proto_rawDescOnce.Do(func() {
		file_proto_management_v1_secrets_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_management_v1_secrets_proto_rawDesc), len(file_proto_management_v1_secrets_proto_rawDesc)))
	})
	return file_proto_management_v1_secrets_proto_rawDescData
}

var file_proto_management_v1_secrets_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_management_v1_secrets_proto_goTypes = []any{
	(*SetSecretRequest)(nil),  // 0: graphene.management.v1.SetSecretRequest
	(*SetSecretResponse)(nil), // 1: graphene.management.v1.SetSecretResponse
}
var file_proto_management_v1_secrets_proto_depIdxs = []int32{
	0, // 0: graphene.management.v1.SecretsAPI.SetSecret:input_type -> graphene.management.v1.SetSecretRequest
	1, // 1: graphene.management.v1.SecretsAPI.SetSecret:output_type -> graphene.management.v1.SetSecretResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_management_v1_secrets_proto_init() }
func file_proto_management_v1_secrets_proto_init() {
	if File_proto_management_v1_secrets_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_management_v1_secrets_proto_rawDesc), len(file_proto_management_v1_secrets_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_management_v1_secrets_proto_goTypes,
		DependencyIndexes: file_proto_management_v1_secrets_proto_depIdxs,
		MessageInfos:      file_proto_management_v1_secrets_proto_msgTypes,
	}.Build()
	File_proto_management_v1_secrets_proto = out.File
	file_proto_management_v1_secrets_proto_goTypes = nil
	file_proto_management_v1_secrets_proto_depIdxs = nil
}
