// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: proto/management/v1/source.proto

package managementv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadSourceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Pipeline the uploaded tree is meant for; the upload area is per
	// pipeline, and a revision materialization builds from it.
	PipelineId string `protobuf:"bytes,1,opt,name=pipeline_id,json=pipelineId,proto3" json:"pipeline_id,omitempty"`
	// The tree as tar.gz.
	Source        []byte `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadSourceRequest) Reset() {
	*x = UploadSourceRequest{}
	mi := &file_proto_management_v1_source_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadSourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadSourceRequest) ProtoMessage() {}

func (x *UploadSourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_v1_source_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadSourceRequest.ProtoReflect.Descriptor instead.
func (*UploadSourceRequest) Descriptor() ([]byte, []int) {
	return file_proto_management_v1_source_proto_rawDescGZIP(), []int{0}
}

func (x *UploadSourceRequest) GetPipelineId() string {
	if x != nil {
		return x.PipelineId
	}
	return ""
}

func (x *UploadSourceRequest) GetSource() []byte {
	if x != nil {
		return x.Source
	}
	return nil
}

type UploadSourceResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Location is where the tree was stored; a declaration or a sync
	// command carries this reference instead of the bytes.
	Location      string `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	Digest        string `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadSourceResponse) Reset() {
	*x = UploadSourceResponse{}
	mi := &file_proto_management_v1_source_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadSourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadSourceResponse) ProtoMessage() {}

func (x *UploadSourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_v1_source_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadSourceResponse.ProtoReflect.Descriptor instead.
func (*UploadSourceResponse) Descriptor() ([]byte, []int) {
	return file_proto_management_v1_source_proto_rawDescGZIP(), []int{1}
}

func (x *UploadSourceResponse) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *UploadSourceResponse) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

type DownloadSourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadSourceRequest) Reset() {
	*x = DownloadSourceRequest{}
	mi := &file_proto_management_v1_source_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadSourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadSourceRequest) ProtoMessage() {}

func (x *DownloadSourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_v1_source_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadSourceRequest.ProtoReflect.Descriptor instead.
func (*DownloadSourceRequest) Descriptor() ([]byte, []int) {
	return file_proto_management_v1_source_proto_rawDescGZIP(), []int{2}
}

func (x *DownloadSourceRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type DownloadSourceChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadSourceChunk) Reset() {
	*x = DownloadSourceChunk{}
	mi := &file_proto_management_v1_source_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadSourceChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadSourceChunk) ProtoMessage() {}

func (x *DownloadSourceChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_v1_source_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadSourceChunk.ProtoReflect.Descriptor instead.
func (*DownloadSourceChunk) Descriptor() ([]byte, []int) {
	return file_proto_management_v1_source_proto_rawDescGZIP(), []int{3}
}

func (x *DownloadSourceChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ListRuntimesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRuntimesRequest) Reset() {
	*x = ListRuntimesRequest{}
	mi := &file_proto_management_v1_source_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRuntimesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRuntimesRequest) ProtoMessage() {}

func (x *ListRuntimesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_v1_source_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRuntimesRequest.ProtoReflect.Descriptor instead.
func (*ListRuntimesRequest) Descriptor() ([]byte, []int) {
	return file_proto_management_v1_source_proto_rawDescGZIP(), []int{4}
}

type ListRuntimesResponse struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Runtimes      []*ListRuntimesResponse_Runtime `protobuf:"bytes,1,rep,name=runtimes,proto3" json:"runtimes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRuntimesResponse) Reset() {
	*x = ListRuntimesResponse{}
	mi := &file_proto_management_v1_source_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRuntimesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRuntimesResponse) ProtoMessage() {}

func (x *ListRuntimesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_v1_source_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRuntimesResponse.ProtoReflect.Descriptor instead.
func (*ListRuntimesResponse) Descriptor() ([]byte, []int) {
	return file_proto_management_v1_source_proto_rawDescGZIP(), []int{5}
}

func (x *ListRuntimesResponse) GetRuntimes() []*ListRuntimesResponse_Runtime {
	if x != nil {
		return x.Runtimes
	}
	return nil
}

type ListFilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesRequest) Reset() {
	*x = ListFilesRequest{}
	mi := &file_proto_management_v1_source_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesRequest) ProtoMessage() {}

func (x *ListFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_v1_source_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesRequest.ProtoReflect.Descriptor instead.
func (*ListFilesRequest) Descriptor() ([]byte, []int) {
	return file_proto_management_v1_source_proto_rawDescGZIP(), []int{6}
}

func (x *ListFilesRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type ListFilesResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Files         []*ListFilesResponse_File `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	TreeDigest    string                    `protobuf:"bytes,2,opt,name=tree_digest,json=treeDigest,proto3" json:"tree_digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesResponse) Reset() {
	*x = ListFilesResponse{}
	mi := &file_proto_management_v1_source_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesResponse) ProtoMessage() {}

func (x *ListFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_v1_source_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesResponse.ProtoReflect.Descriptor instead.
func (*ListFilesResponse) Descriptor() ([]byte, []int) {
	return file_proto_management_v1_source_proto_rawDescGZIP(), []int{7}
}

func (x *ListFilesResponse) GetFiles() []*ListFilesResponse_File {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *ListFilesResponse) GetTreeDigest() string {
	if x != nil {
		return x.TreeDigest
	}
	return ""
}

type ReadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileRequest) Reset() {
	*x = ReadFileRequest{}
	mi := &file_proto_management_v1_source_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileRequest) ProtoMessage() {}

func (x *ReadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_v1_source_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileRequest.ProtoReflect.Descriptor instead.
func (*ReadFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_management_v1_source_proto_rawDescGZIP(), []int{8}
}

func (x *ReadFileRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ReadFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ReadFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []byte                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileResponse) Reset() {
	*x = ReadFileResponse{}
	mi := &file_proto_management_v1_source_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileResponse) ProtoMessage() {}

func (x *ReadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_v1_source_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileResponse.ProtoReflect.Descriptor instead.
func (*ReadFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_management_v1_source_proto_rawDescGZIP(), []int{9}
}

func (x *ReadFileResponse) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type ListRuntimesResponse_Runtime struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	IsDefault     bool                   `protobuf:"varint,4,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRuntimesResponse_Runtime) Reset() {
	*x = ListRuntimesResponse_Runtime{}
	mi := &file_proto_management_v1_source_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRuntimesResponse_Runtime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRuntimesResponse_Runtime) ProtoMessage() {}

func (x *ListRuntimesResponse_Runtime) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_v1_source_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRuntimesResponse_Runtime.ProtoReflect.Descriptor instead.
func (*ListRuntimesResponse_Runtime) Descriptor() ([]byte, []int) {
	return file_proto_management_v1_source_proto_rawDescGZIP(), []int{5, 0}
}

func (x *ListRuntimesResponse_Runtime) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListRuntimesResponse_Runtime) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ListRuntimesResponse_Runtime) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ListRuntimesResponse_Runtime) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

type ListFilesResponse_File struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesResponse_File) Reset() {
	*x = ListFilesResponse_File{}
	mi := &file_proto_management_v1_source_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesResponse_File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesResponse_File) ProtoMessage() {}

func (x *ListFilesResponse_File) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_v1_source_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesResponse_File.ProtoReflect.Descriptor instead.
func (*ListFilesResponse_File) Descriptor() ([]byte, []int) {
	return file_proto_management_v1_source_proto_rawDescGZIP(), []int{7, 0}
}

func (x *ListFilesResponse_File) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ListFilesResponse_File) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

var File_proto_management_v1_source_proto protoreflect.FileDescriptor

const file_proto_management_v1_source_proto_rawDesc = "" +
	"\n" +
	" proto/management/v1/source.proto\x12\x16graphene.management.v1\"N\n" +
	"\x13UploadSourceRequest\x12\x1f\n" +
	"\vpipeline_id\x18\x01 \x01(\tR\n" +
	"pipelineId\x12\x16\n" +
	"\x06source\x18\x02 \x01(\fR\x06source\"J\n" +
	"\x14UploadSourceResponse\x12\x1a\n" +
	"\blocation\x18\x01 \x01(\tR\blocation\x12\x16\n" +
	"\x06digest\x18\x02 \x01(\tR\x06digest\"/\n" +
	"\x15DownloadSourceRequest\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\")\n" +
	"\x13DownloadSourceChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\x15\n" +
	"\x13ListRuntimesRequest\"\xd6\x01\n" +
	"\x14ListRuntimesResponse\x12P\n" +
	"\bruntimes\x18\x01 \x03(\v24.graphene.management.v1.ListRuntimesResponse.RuntimeR\bruntimes\x1al\n" +
	"\aRuntime\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x1d\n" +
	"\n" +
	"is_default\x18\x04 \x01(\bR\tisDefault\"*\n" +
	"\x10ListFilesRequest\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\"\xaa\x01\n" +
	"\x11ListFilesResponse\x12D\n" +
	"\x05files\x18\x01 \x03(\v2..graphene.management.v1.ListFilesResponse.FileR\x05files\x12\x1f\n" +
	"\vtree_digest\x18\x02 \x01(\tR\n" +
	"treeDigest\x1a.\n" +
	"\x04File\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\"=\n" +
	"\x0fReadFileRequest\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\",\n" +
	"\x10ReadFileResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\fR\acontent2\x92\x04\n" +
	"\tSourceAPI\x12i\n" +
	"\fUploadSource\x12+.graphene.management.v1.UploadSourceRequest\x1a,.graphene.management.v1.UploadSourceResponse\x12n\n" +
	"\x0eDownloadSource\x12-.graphene.management.v1.DownloadSourceRequest\x1a+.graphene.management.v1.DownloadSourceChunk0\x01\x12i\n" +
	"\fListRuntimes\x12+.graphene.management.v1.ListRuntimesRequest\x1a,.graphene.management.v1.ListRuntimesResponse\x12`\n" +
	"\tListFiles\x12(.graphene.management.v1.ListFilesRequest\x1a).graphene.management.v1.ListFilesResponse\x12]\n" +
	"\bReadFile\x12'.graphene.management.v1.ReadFileRequest\x1a(.graphene.management.v1.ReadFileResponseBFZDgithub.com/graphene-ci/graphene/pkg/proto/management/v1;managementv1b\x06proto3"

var (
	file_proto_management_v1_source_proto_rawDescOnce sync.Once
	file_proto_management_v1_source_proto_rawDescData []byte
)

func file_proto_management_v1_source_proto_rawDescGZIP() []byte {
	file_proto_management_v1_source_proto_rawDescOnce.Do(func() {
		file_proto_management_v1_source_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_management_v1_source_proto_rawDesc), len(file_proto_management_v1_source_proto_rawDesc)))
	})
	return file_proto_management_v1_source_proto_rawDescData
}

var file_proto_management_v1_source_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_management_v1_source_proto_goTypes = []any{
	(*UploadSourceRequest)(nil),          // 0: graphene.management.v1.UploadSourceRequest
	(*UploadSourceResponse)(nil),         // 1: graphene.management.v1.UploadSourceResponse
	(*DownloadSourceRequest)(nil),        // 2: graphene.management.v1.DownloadSourceRequest
	(*DownloadSourceChunk)(nil),          // 3: graphene.management.v1.DownloadSourceChunk
	(*ListRuntimesRequest)(nil),          // 4: graphene.management.v1.ListRuntimesRequest
	(*ListRuntimesResponse)(nil),         // 5: graphene.management.v1.ListRuntimesResponse
	(*ListFilesRequest)(nil),             // 6: graphene.management.v1.ListFilesRequest
	(*ListFilesResponse)(nil),            // 7: graphene.management.v1.ListFilesResponse
	(*ReadFileRequest)(nil),              // 8: graphene.management.v1.ReadFileRequest
	(*ReadFileResponse)(nil),             // 9: graphene.management.v1.ReadFileResponse
	(*ListRuntimesResponse_Runtime)(nil), // 10: graphene.management.v1.ListRuntimesResponse.Runtime
	(*ListFilesResponse_File)(nil),       // 11: graphene.management.v1.ListFilesResponse.File
}
var file_proto_management_v1_source_proto_depIdxs = []int32{
	10, // 0: graphene.management.v1.ListRuntimesResponse.runtimes:type_name -> graphene.management.v1.ListRuntimesResponse.Runtime
	11, // 1: graphene.management.v1.ListFilesResponse.files:type_name -> graphene.management.v1.ListFilesResponse.File
	0,  // 2: graphene.management.v1.SourceAPI.UploadSource:input_type -> graphene.management.v1.UploadSourceRequest
	2,  // 3: graphene.management.v1.SourceAPI.DownloadSource:input_type -> graphene.management.v1.DownloadSourceRequest
	4,  // 4: graphene.management.v1.SourceAPI.ListRuntimes:input_type -> graphene.management.v1.ListRuntimesRequest
	6,  // 5: graphene.management.v1.SourceAPI.ListFiles:input_type -> graphene.management.v1.ListFilesRequest
	8,  // 6: graphene.management.v1.SourceAPI.ReadFile:input_type -> graphene.management.v1.ReadFileRequest
	1,  // 7: graphene.management.v1.SourceAPI.UploadSource:output_type -> graphene.management.v1.UploadSourceResponse
	3,  // 8: graphene.management.v1.SourceAPI.DownloadSource:output_type -> graphene.management.v1.DownloadSourceChunk
	5,  // 9: graphene.management.v1.SourceAPI.ListRuntimes:output_type -> graphene.management.v1.ListRuntimesResponse
	7,  // 10: graphene.management.v1.SourceAPI.ListFiles:output_type -> graphene.management.v1.ListFilesResponse
	9,  // 11: graphene.management.v1.SourceAPI.ReadFile:output_type -> graphene.management.v1.ReadFileResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_management_v1_source_proto_init() }
func file_proto_management_v1_source_proto_init() {
	if File_proto_management_v1_source_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_management_v1_source_proto_rawDesc), len(file_proto_management_v1_source_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_management_v1_source_proto_goTypes,
		DependencyIndexes: file_proto_management_v1_source_proto_depIdxs,
		MessageInfos:      file_proto_management_v1_source_proto_msgTypes,
	}.Build()
	File_proto_management_v1_source_proto = out.File
	file_proto_management_v1_source_proto_goTypes = nil
	file_proto_management_v1_source_proto_depIdxs = nil
}
