// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: proto/management/v1/source.proto

package managementv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SourceAPI_UploadSource_FullMethodName   = "/graphene.management.v1.SourceAPI/UploadSource"
	SourceAPI_DownloadSource_FullMethodName = "/graphene.management.v1.SourceAPI/DownloadSource"
	SourceAPI_ListRuntimes_FullMethodName   = "/graphene.management.v1.SourceAPI/ListRuntimes"
	SourceAPI_ListFiles_FullMethodName      = "/graphene.management.v1.SourceAPI/ListFiles"
	SourceAPI_ReadFile_FullMethodName       = "/graphene.management.v1.SourceAPI/ReadFile"
	SourceAPI_WriteFile_FullMethodName      = "/graphene.management.v1.SourceAPI/WriteFile"
	SourceAPI_DeleteFile_FullMethodName     = "/graphene.management.v1.SourceAPI/DeleteFile"
)

// SourceAPIClient is the client API for SourceAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SourceAPI is the pipeline's SOURCE side: the bytes of a project's
// working tree. The pipeline itself is an ordinary record — declared
// with Apply, changed with Invoke, read with Get — so what stays here
// is only what a command cannot carry: bytes, and questions about the
// installation rather than about a record.
type SourceAPIClient interface {
	// UploadSource stores a source tree and returns its reference. Bytes
	// do not travel in commands: a command's payload becomes an event in
	// the record's history, and a source tree would bury it.
	UploadSource(ctx context.Context, in *UploadSourceRequest, opts ...grpc.CallOption) (*UploadSourceResponse, error)
	// DownloadSource hands back the pipeline's current working tree.
	DownloadSource(ctx context.Context, in *DownloadSourceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DownloadSourceChunk], error)
	// ListRuntimes answers "which languages can I write a pipeline in
	// on THIS installation".
	ListRuntimes(ctx context.Context, in *ListRuntimesRequest, opts ...grpc.CallOption) (*ListRuntimesResponse, error)
	// The working tree is EDITABLE: Studio reads and writes files
	// straight into the pipeline's tree, and every write is durable —
	// that is the whole point of the tree living on the server.
	ListFiles(ctx context.Context, in *ListFilesRequest, opts ...grpc.CallOption) (*ListFilesResponse, error)
	ReadFile(ctx context.Context, in *ReadFileRequest, opts ...grpc.CallOption) (*ReadFileResponse, error)
	WriteFile(ctx context.Context, in *WriteFileRequest, opts ...grpc.CallOption) (*WriteFileResponse, error)
	DeleteFile(ctx context.Context, in *DeleteFileRequest, opts ...grpc.CallOption) (*WriteFileResponse, error)
}

type sourceAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewSourceAPIClient(cc grpc.ClientConnInterface) SourceAPIClient {
	return &sourceAPIClient{cc}
}

func (c *sourceAPIClient) UploadSource(ctx context.Context, in *UploadSourceRequest, opts ...grpc.CallOption) (*UploadSourceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadSourceResponse)
	err := c.cc.Invoke(ctx, SourceAPI_UploadSource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sourceAPIClient) DownloadSource(ctx context.Context, in *DownloadSourceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DownloadSourceChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SourceAPI_ServiceDesc.Streams[0], SourceAPI_DownloadSource_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DownloadSourceRequest, DownloadSourceChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SourceAPI_DownloadSourceClient = grpc.ServerStreamingClient[DownloadSourceChunk]

func (c *sourceAPIClient) ListRuntimes(ctx context.Context, in *ListRuntimesRequest, opts ...grpc.CallOption) (*ListRuntimesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRuntimesResponse)
	err := c.cc.Invoke(ctx, SourceAPI_ListRuntimes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sourceAPIClient) ListFiles(ctx context.Context, in *ListFilesRequest, opts ...grpc.CallOption) (*ListFilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFilesResponse)
	err := c.cc.Invoke(ctx, SourceAPI_ListFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sourceAPIClient) ReadFile(ctx context.Context, in *ReadFileRequest, opts ...grpc.CallOption) (*ReadFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadFileResponse)
	err := c.cc.Invoke(ctx, SourceAPI_ReadFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sourceAPIClient) WriteFile(ctx context.Context, in *WriteFileRequest, opts ...grpc.CallOption) (*WriteFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteFileResponse)
	err := c.cc.Invoke(ctx, SourceAPI_WriteFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sourceAPIClient) DeleteFile(ctx context.Context, in *DeleteFileRequest, opts ...grpc.CallOption) (*WriteFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteFileResponse)
	err := c.cc.Invoke(ctx, SourceAPI_DeleteFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SourceAPIServer is the server API for SourceAPI service.
// All implementations must embed UnimplementedSourceAPIServer
// for forward compatibility.
//
// SourceAPI is the pipeline's SOURCE side: the bytes of a project's
// working tree. The pipeline itself is an ordinary record — declared
// with Apply, changed with Invoke, read with Get — so what stays here
// is only what a command cannot carry: bytes, and questions about the
// installation rather than about a record.
type SourceAPIServer interface {
	// UploadSource stores a source tree and returns its reference. Bytes
	// do not travel in commands: a command's payload becomes an event in
	// the record's history, and a source tree would bury it.
	UploadSource(context.Context, *UploadSourceRequest) (*UploadSourceResponse, error)
	// DownloadSource hands back the pipeline's current working tree.
	DownloadSource(*DownloadSourceRequest, grpc.ServerStreamingServer[DownloadSourceChunk]) error
	// ListRuntimes answers "which languages can I write a pipeline in
	// on THIS installation".
	ListRuntimes(context.Context, *ListRuntimesRequest) (*ListRuntimesResponse, error)
	// The working tree is EDITABLE: Studio reads and writes files
	// straight into the pipeline's tree, and every write is durable —
	// that is the whole point of the tree living on the server.
	ListFiles(context.Context, *ListFilesRequest) (*ListFilesResponse, error)
	ReadFile(context.Context, *ReadFileRequest) (*ReadFileResponse, error)
	WriteFile(context.Context, *WriteFileRequest) (*WriteFileResponse, error)
	DeleteFile(context.Context, *DeleteFileRequest) (*WriteFileResponse, error)
	mustEmbedUnimplementedSourceAPIServer()
}

// UnimplementedSourceAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSourceAPIServer struct{}

func (UnimplementedSourceAPIServer) UploadSource(context.Context, *UploadSourceRequest) (*UploadSourceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadSource not implemented")
}
func (UnimplementedSourceAPIServer) DownloadSource(*DownloadSourceRequest, grpc.ServerStreamingServer[DownloadSourceChunk]) error {
	return status.Error(codes.Unimplemented, "method DownloadSource not implemented")
}
func (UnimplementedSourceAPIServer) ListRuntimes(context.Context, *ListRuntimesRequest) (*ListRuntimesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRuntimes not implemented")
}
func (UnimplementedSourceAPIServer) ListFiles(context.Context, *ListFilesRequest) (*ListFilesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFiles not implemented")
}
func (UnimplementedSourceAPIServer) ReadFile(context.Context, *ReadFileRequest) (*ReadFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadFile not implemented")
}
func (UnimplementedSourceAPIServer) WriteFile(context.Context, *WriteFileRequest) (*WriteFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WriteFile not implemented")
}
func (UnimplementedSourceAPIServer) DeleteFile(context.Context, *DeleteFileRequest) (*WriteFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteFile not implemented")
}
func (UnimplementedSourceAPIServer) mustEmbedUnimplementedSourceAPIServer() {}
func (UnimplementedSourceAPIServer) testEmbeddedByValue()                   {}

// UnsafeSourceAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SourceAPIServer will
// result in compilation errors.
type UnsafeSourceAPIServer interface {
	mustEmbedUnimplementedSourceAPIServer()
}

func RegisterSourceAPIServer(s grpc.ServiceRegistrar, srv SourceAPIServer) {
	// If the following call panics, it indicates UnimplementedSourceAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SourceAPI_ServiceDesc, srv)
}

func _SourceAPI_UploadSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SourceAPIServer).UploadSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SourceAPI_UploadSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SourceAPIServer).UploadSource(ctx, req.(*UploadSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SourceAPI_DownloadSource_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownloadSourceRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SourceAPIServer).DownloadSource(m, &grpc.GenericServerStream[DownloadSourceRequest, DownloadSourceChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SourceAPI_DownloadSourceServer = grpc.ServerStreamingServer[DownloadSourceChunk]

func _SourceAPI_ListRuntimes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRuntimesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SourceAPIServer).ListRuntimes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SourceAPI_ListRuntimes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SourceAPIServer).ListRuntimes(ctx, req.(*ListRuntimesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SourceAPI_ListFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SourceAPIServer).ListFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SourceAPI_ListFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SourceAPIServer).ListFiles(ctx, req.(*ListFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SourceAPI_ReadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SourceAPIServer).ReadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SourceAPI_ReadFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SourceAPIServer).ReadFile(ctx, req.(*ReadFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SourceAPI_WriteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SourceAPIServer).WriteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SourceAPI_WriteFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SourceAPIServer).WriteFile(ctx, req.(*WriteFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SourceAPI_DeleteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SourceAPIServer).DeleteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SourceAPI_DeleteFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SourceAPIServer).DeleteFile(ctx, req.(*DeleteFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SourceAPI_ServiceDesc is the grpc.ServiceDesc for SourceAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SourceAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "graphene.management.v1.SourceAPI",
	HandlerType: (*SourceAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UploadSource",
			Handler:    _SourceAPI_UploadSource_Handler,
		},
		{
			MethodName: "ListRuntimes",
			Handler:    _SourceAPI_ListRuntimes_Handler,
		},
		{
			MethodName: "ListFiles",
			Handler:    _SourceAPI_ListFiles_Handler,
		},
		{
			MethodName: "ReadFile",
			Handler:    _SourceAPI_ReadFile_Handler,
		},
		{
			MethodName: "WriteFile",
			Handler:    _SourceAPI_WriteFile_Handler,
		},
		{
			MethodName: "DeleteFile",
			Handler:    _SourceAPI_DeleteFile_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DownloadSource",
			Handler:       _SourceAPI_DownloadSource_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/management/v1/source.proto",
}
