// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: proto/management/v1/vars.proto

package managementv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetVarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetVarRequest) Reset() {
	*x = SetVarRequest{}
	mi := &file_proto_management_v1_vars_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetVarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetVarRequest) ProtoMessage() {}

func (x *SetVarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_v1_vars_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetVarRequest.ProtoReflect.Descriptor instead.
func (*SetVarRequest) Descriptor() ([]byte, []int) {
	return file_proto_management_v1_vars_proto_rawDescGZIP(), []int{0}
}

func (x *SetVarRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SetVarRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SetVarResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetVarResponse) Reset() {
	*x = SetVarResponse{}
	mi := &file_proto_management_v1_vars_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetVarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetVarResponse) ProtoMessage() {}

func (x *SetVarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_v1_vars_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetVarResponse.ProtoReflect.Descriptor instead.
func (*SetVarResponse) Descriptor() ([]byte, []int) {
	return file_proto_management_v1_vars_proto_rawDescGZIP(), []int{1}
}

type DeleteVarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVarRequest) Reset() {
	*x = DeleteVarRequest{}
	mi := &file_proto_management_v1_vars_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVarRequest) ProtoMessage() {}

func (x *DeleteVarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_v1_vars_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVarRequest.ProtoReflect.Descriptor instead.
func (*DeleteVarRequest) Descriptor() ([]byte, []int) {
	return file_proto_management_v1_vars_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteVarRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteVarResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVarResponse) Reset() {
	*x = DeleteVarResponse{}
	mi := &file_proto_management_v1_vars_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVarResponse) ProtoMessage() {}

func (x *DeleteVarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_v1_vars_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVarResponse.ProtoReflect.Descriptor instead.
func (*DeleteVarResponse) Descriptor() ([]byte, []int) {
	return file_proto_management_v1_vars_proto_rawDescGZIP(), []int{3}
}

type ListVarsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVarsRequest) Reset() {
	*x = ListVarsRequest{}
	mi := &file_proto_management_v1_vars_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVarsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVarsRequest) ProtoMessage() {}

func (x *ListVarsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_v1_vars_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVarsRequest.ProtoReflect.Descriptor instead.
func (*ListVarsRequest) Descriptor() ([]byte, []int) {
	return file_proto_management_v1_vars_proto_rawDescGZIP(), []int{4}
}

type ListVarsResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Vars          []*ListVarsResponse_Var `protobuf:"bytes,1,rep,name=vars,proto3" json:"vars,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVarsResponse) Reset() {
	*x = ListVarsResponse{}
	mi := &file_proto_management_v1_vars_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVarsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVarsResponse) ProtoMessage() {}

func (x *ListVarsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_v1_vars_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVarsResponse.ProtoReflect.Descriptor instead.
func (*ListVarsResponse) Descriptor() ([]byte, []int) {
	return file_proto_management_v1_vars_proto_rawDescGZIP(), []int{5}
}

func (x *ListVarsResponse) GetVars() []*ListVarsResponse_Var {
	if x != nil {
		return x.Vars
	}
	return nil
}

type ListVarsResponse_Var struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVarsResponse_Var) Reset() {
	*x = ListVarsResponse_Var{}
	mi := &file_proto_management_v1_vars_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVarsResponse_Var) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVarsResponse_Var) ProtoMessage() {}

func (x *ListVarsResponse_Var) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_v1_vars_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVarsResponse_Var.ProtoReflect.Descriptor instead.
func (*ListVarsResponse_Var) Descriptor() ([]byte, []int) {
	return file_proto_management_v1_vars_proto_rawDescGZIP(), []int{5, 0}
}

func (x *ListVarsResponse_Var) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListVarsResponse_Var) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_proto_management_v1_vars_proto protoreflect.FileDescriptor

const file_proto_management_v1_vars_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/management/v1/vars.proto\x12\x16graphene.management.v1\"9\n" +
	"\rSetVarRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\x10\n" +
	"\x0eSetVarResponse\"&\n" +
	"\x10DeleteVarRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x13\n" +
	"\x11DeleteVarResponse\"\x11\n" +
	"\x0fListVarsRequest\"\x85\x01\n" +
	"\x10ListVarsResponse\x12@\n" +
	"\x04vars\x18\x01 \x03(\v2,.graphene.management.v1.ListVarsResponse.VarR\x04vars\x1a/\n" +
	"\x03Var\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value2\xa3\x02\n" +
	"\aVarsAPI\x12W\n" +
	"\x06SetVar\x12%.graphene.management.v1.SetVarRequest\x1a&.graphene.management.v1.SetVarResponse\x12`\n" +
	"\tDeleteVar\x12(.graphene.management.v1.DeleteVarRequest\x1a).graphene.management.v1.DeleteVarResponse\x12]\n" +
	"\bListVars\x12'.graphene.management.v1.ListVarsRequest\x1a(.graphene.management.v1.ListVarsResponseBFZDgithub.com/graphene-ci/graphene/pkg/proto/management/v1;managementv1b\x06proto3"

var (
	file_proto_management_v1_vars_proto_rawDescOnce sync.Once
	file_proto_management_v1_vars_proto_rawDescData []byte
)

func file_proto_management_v1_vars_proto_rawDescGZIP() []byte {
	file_proto_management_v1_vars_proto_rawDescOnce.Do(func() {
		file_proto_management_v1_vars_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_management_v1_vars_proto_rawDesc), len(file_proto_management_v1_vars_proto_rawDesc)))
	})
	return file_proto_management_v1_vars_proto_rawDescData
}

var file_proto_management_v1_vars_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_management_v1_vars_proto_goTypes = []any{
	(*SetVarRequest)(nil),        // 0: graphene.management.v1.SetVarRequest
	(*SetVarResponse)(nil),       // 1: graphene.management.v1.SetVarResponse
	(*DeleteVarRequest)(nil),     // 2: graphene.management.v1.DeleteVarRequest
	(*DeleteVarResponse)(nil),    // 3: graphene.management.v1.DeleteVarResponse
	(*ListVarsRequest)(nil),      // 4: graphene.management.v1.ListVarsRequest
	(*ListVarsResponse)(nil),     // 5: graphene.management.v1.ListVarsResponse
	(*ListVarsResponse_Var)(nil), // 6: graphene.management.v1.ListVarsResponse.Var
}
var file_proto_management_v1_vars_proto_depIdxs = []int32{
	6, // 0: graphene.management.v1.ListVarsResponse.vars:type_name -> graphene.management.v1.ListVarsResponse.Var
	0, // 1: graphene.management.v1.VarsAPI.SetVar:input_type -> graphene.management.v1.SetVarRequest
	2, // 2: graphene.management.v1.VarsAPI.DeleteVar:input_type -> graphene.management.v1.DeleteVarRequest
	4, // 3: graphene.management.v1.VarsAPI.ListVars:input_type -> graphene.management.v1.ListVarsRequest
	1, // 4: graphene.management.v1.VarsAPI.SetVar:output_type -> graphene.management.v1.SetVarResponse
	3, // 5: graphene.management.v1.VarsAPI.DeleteVar:output_type -> graphene.management.v1.DeleteVarResponse
	5, // 6: graphene.management.v1.VarsAPI.ListVars:output_type -> graphene.management.v1.ListVarsResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_management_v1_vars_proto_init() }
func file_proto_management_v1_vars_proto_init() {
	if File_proto_management_v1_vars_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_management_v1_vars_proto_rawDesc), len(file_proto_management_v1_vars_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_management_v1_vars_proto_goTypes,
		DependencyIndexes: file_proto_management_v1_vars_proto_depIdxs,
		MessageInfos:      file_proto_management_v1_vars_proto_msgTypes,
	}.Build()
	File_proto_management_v1_vars_proto = out.File
	file_proto_management_v1_vars_proto_goTypes = nil
	file_proto_management_v1_vars_proto_depIdxs = nil
}
