// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: proto/management/v1/workspaces.proto

package managementv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkspacesAPI_CreateWorkspace_FullMethodName = "/graphene.management.v1.WorkspacesAPI/CreateWorkspace"
	WorkspacesAPI_SyncWorkspace_FullMethodName   = "/graphene.management.v1.WorkspacesAPI/SyncWorkspace"
	WorkspacesAPI_DownloadSource_FullMethodName  = "/graphene.management.v1.WorkspacesAPI/DownloadSource"
)

// WorkspacesAPIClient is the client API for WorkspacesAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// WorkspacesAPI administers WORKSPACES: a project's working area and
// the root of its life. A workspace has one source — a Git checkout or
// an uploaded tree — a runtime, a working tree kept on the server, and
// at most one pipeline. Listing, reading and deleting go through the
// ordinary ResourcesAPI: a workspace is a record like any other.
type WorkspacesAPIClient interface {
	CreateWorkspace(ctx context.Context, in *CreateWorkspaceRequest, opts ...grpc.CallOption) (*CreateWorkspaceResponse, error)
	// SyncWorkspace re-resolves the source: a Git workspace fetches its
	// ref again, a snapshot workspace takes a freshly uploaded tree.
	SyncWorkspace(ctx context.Context, in *SyncWorkspaceRequest, opts ...grpc.CallOption) (*SyncWorkspaceResponse, error)
	// DownloadSource hands back the workspace's current working tree.
	DownloadSource(ctx context.Context, in *DownloadSourceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DownloadSourceChunk], error)
}

type workspacesAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkspacesAPIClient(cc grpc.ClientConnInterface) WorkspacesAPIClient {
	return &workspacesAPIClient{cc}
}

func (c *workspacesAPIClient) CreateWorkspace(ctx context.Context, in *CreateWorkspaceRequest, opts ...grpc.CallOption) (*CreateWorkspaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateWorkspaceResponse)
	err := c.cc.Invoke(ctx, WorkspacesAPI_CreateWorkspace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspacesAPIClient) SyncWorkspace(ctx context.Context, in *SyncWorkspaceRequest, opts ...grpc.CallOption) (*SyncWorkspaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncWorkspaceResponse)
	err := c.cc.Invoke(ctx, WorkspacesAPI_SyncWorkspace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspacesAPIClient) DownloadSource(ctx context.Context, in *DownloadSourceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DownloadSourceChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorkspacesAPI_ServiceDesc.Streams[0], WorkspacesAPI_DownloadSource_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DownloadSourceRequest, DownloadSourceChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkspacesAPI_DownloadSourceClient = grpc.ServerStreamingClient[DownloadSourceChunk]

// WorkspacesAPIServer is the server API for WorkspacesAPI service.
// All implementations must embed UnimplementedWorkspacesAPIServer
// for forward compatibility.
//
// WorkspacesAPI administers WORKSPACES: a project's working area and
// the root of its life. A workspace has one source — a Git checkout or
// an uploaded tree — a runtime, a working tree kept on the server, and
// at most one pipeline. Listing, reading and deleting go through the
// ordinary ResourcesAPI: a workspace is a record like any other.
type WorkspacesAPIServer interface {
	CreateWorkspace(context.Context, *CreateWorkspaceRequest) (*CreateWorkspaceResponse, error)
	// SyncWorkspace re-resolves the source: a Git workspace fetches its
	// ref again, a snapshot workspace takes a freshly uploaded tree.
	SyncWorkspace(context.Context, *SyncWorkspaceRequest) (*SyncWorkspaceResponse, error)
	// DownloadSource hands back the workspace's current working tree.
	DownloadSource(*DownloadSourceRequest, grpc.ServerStreamingServer[DownloadSourceChunk]) error
	mustEmbedUnimplementedWorkspacesAPIServer()
}

// UnimplementedWorkspacesAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkspacesAPIServer struct{}

func (UnimplementedWorkspacesAPIServer) CreateWorkspace(context.Context, *CreateWorkspaceRequest) (*CreateWorkspaceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateWorkspace not implemented")
}
func (UnimplementedWorkspacesAPIServer) SyncWorkspace(context.Context, *SyncWorkspaceRequest) (*SyncWorkspaceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncWorkspace not implemented")
}
func (UnimplementedWorkspacesAPIServer) DownloadSource(*DownloadSourceRequest, grpc.ServerStreamingServer[DownloadSourceChunk]) error {
	return status.Error(codes.Unimplemented, "method DownloadSource not implemented")
}
func (UnimplementedWorkspacesAPIServer) mustEmbedUnimplementedWorkspacesAPIServer() {}
func (UnimplementedWorkspacesAPIServer) testEmbeddedByValue()                       {}

// UnsafeWorkspacesAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkspacesAPIServer will
// result in compilation errors.
type UnsafeWorkspacesAPIServer interface {
	mustEmbedUnimplementedWorkspacesAPIServer()
}

func RegisterWorkspacesAPIServer(s grpc.ServiceRegistrar, srv WorkspacesAPIServer) {
	// If the following call panics, it indicates UnimplementedWorkspacesAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkspacesAPI_ServiceDesc, srv)
}

func _WorkspacesAPI_CreateWorkspace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWorkspaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspacesAPIServer).CreateWorkspace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspacesAPI_CreateWorkspace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspacesAPIServer).CreateWorkspace(ctx, req.(*CreateWorkspaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspacesAPI_SyncWorkspace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncWorkspaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspacesAPIServer).SyncWorkspace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspacesAPI_SyncWorkspace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspacesAPIServer).SyncWorkspace(ctx, req.(*SyncWorkspaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspacesAPI_DownloadSource_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownloadSourceRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WorkspacesAPIServer).DownloadSource(m, &grpc.GenericServerStream[DownloadSourceRequest, DownloadSourceChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkspacesAPI_DownloadSourceServer = grpc.ServerStreamingServer[DownloadSourceChunk]

// WorkspacesAPI_ServiceDesc is the grpc.ServiceDesc for WorkspacesAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkspacesAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "graphene.management.v1.WorkspacesAPI",
	HandlerType: (*WorkspacesAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateWorkspace",
			Handler:    _WorkspacesAPI_CreateWorkspace_Handler,
		},
		{
			MethodName: "SyncWorkspace",
			Handler:    _WorkspacesAPI_SyncWorkspace_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DownloadSource",
			Handler:       _WorkspacesAPI_DownloadSource_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/management/v1/workspaces.proto",
}
