// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: proto/management/v1/workspaces.proto

package managementv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkspacesAPI_UploadSource_FullMethodName   = "/graphene.management.v1.WorkspacesAPI/UploadSource"
	WorkspacesAPI_DownloadSource_FullMethodName = "/graphene.management.v1.WorkspacesAPI/DownloadSource"
	WorkspacesAPI_ListRuntimes_FullMethodName   = "/graphene.management.v1.WorkspacesAPI/ListRuntimes"
	WorkspacesAPI_ListFiles_FullMethodName      = "/graphene.management.v1.WorkspacesAPI/ListFiles"
	WorkspacesAPI_ReadFile_FullMethodName       = "/graphene.management.v1.WorkspacesAPI/ReadFile"
	WorkspacesAPI_WriteFile_FullMethodName      = "/graphene.management.v1.WorkspacesAPI/WriteFile"
	WorkspacesAPI_DeleteFile_FullMethodName     = "/graphene.management.v1.WorkspacesAPI/DeleteFile"
)

// WorkspacesAPIClient is the client API for WorkspacesAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// WorkspacesAPI administers WORKSPACES: a project's working area and
// the root of its life. A workspace has one source — a Git checkout or
// an uploaded tree — a runtime, a working tree kept on the server, and
// at most one pipeline. Listing, reading and deleting go through the
// ordinary ResourcesAPI: a workspace is a record like any other.
// A workspace is a RECORD: declared with Apply, changed with Invoke,
// read with Get. What stays here is what a command cannot carry —
// bytes, and questions about the installation rather than a record.
type WorkspacesAPIClient interface {
	// UploadSource stores a source tree and returns its reference. Bytes
	// do not travel in commands: a command's payload becomes an event in
	// the record's history, and a source tree would bury it.
	UploadSource(ctx context.Context, in *UploadSourceRequest, opts ...grpc.CallOption) (*UploadSourceResponse, error)
	// DownloadSource hands back the workspace's current working tree.
	DownloadSource(ctx context.Context, in *DownloadSourceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DownloadSourceChunk], error)
	// ListRuntimes answers "which languages can I write a pipeline in
	// on THIS installation".
	ListRuntimes(ctx context.Context, in *ListRuntimesRequest, opts ...grpc.CallOption) (*ListRuntimesResponse, error)
	// The working tree is EDITABLE: Studio reads and writes files
	// straight into the workspace, and every write is durable — that is
	// the whole point of the tree living on the server.
	ListFiles(ctx context.Context, in *ListFilesRequest, opts ...grpc.CallOption) (*ListFilesResponse, error)
	ReadFile(ctx context.Context, in *ReadFileRequest, opts ...grpc.CallOption) (*ReadFileResponse, error)
	WriteFile(ctx context.Context, in *WriteFileRequest, opts ...grpc.CallOption) (*WriteFileResponse, error)
	DeleteFile(ctx context.Context, in *DeleteFileRequest, opts ...grpc.CallOption) (*WriteFileResponse, error)
}

type workspacesAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkspacesAPIClient(cc grpc.ClientConnInterface) WorkspacesAPIClient {
	return &workspacesAPIClient{cc}
}

func (c *workspacesAPIClient) UploadSource(ctx context.Context, in *UploadSourceRequest, opts ...grpc.CallOption) (*UploadSourceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadSourceResponse)
	err := c.cc.Invoke(ctx, WorkspacesAPI_UploadSource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspacesAPIClient) DownloadSource(ctx context.Context, in *DownloadSourceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DownloadSourceChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorkspacesAPI_ServiceDesc.Streams[0], WorkspacesAPI_DownloadSource_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DownloadSourceRequest, DownloadSourceChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkspacesAPI_DownloadSourceClient = grpc.ServerStreamingClient[DownloadSourceChunk]

func (c *workspacesAPIClient) ListRuntimes(ctx context.Context, in *ListRuntimesRequest, opts ...grpc.CallOption) (*ListRuntimesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRuntimesResponse)
	err := c.cc.Invoke(ctx, WorkspacesAPI_ListRuntimes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspacesAPIClient) ListFiles(ctx context.Context, in *ListFilesRequest, opts ...grpc.CallOption) (*ListFilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFilesResponse)
	err := c.cc.Invoke(ctx, WorkspacesAPI_ListFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspacesAPIClient) ReadFile(ctx context.Context, in *ReadFileRequest, opts ...grpc.CallOption) (*ReadFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadFileResponse)
	err := c.cc.Invoke(ctx, WorkspacesAPI_ReadFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspacesAPIClient) WriteFile(ctx context.Context, in *WriteFileRequest, opts ...grpc.CallOption) (*WriteFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteFileResponse)
	err := c.cc.Invoke(ctx, WorkspacesAPI_WriteFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspacesAPIClient) DeleteFile(ctx context.Context, in *DeleteFileRequest, opts ...grpc.CallOption) (*WriteFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteFileResponse)
	err := c.cc.Invoke(ctx, WorkspacesAPI_DeleteFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkspacesAPIServer is the server API for WorkspacesAPI service.
// All implementations must embed UnimplementedWorkspacesAPIServer
// for forward compatibility.
//
// WorkspacesAPI administers WORKSPACES: a project's working area and
// the root of its life. A workspace has one source — a Git checkout or
// an uploaded tree — a runtime, a working tree kept on the server, and
// at most one pipeline. Listing, reading and deleting go through the
// ordinary ResourcesAPI: a workspace is a record like any other.
// A workspace is a RECORD: declared with Apply, changed with Invoke,
// read with Get. What stays here is what a command cannot carry —
// bytes, and questions about the installation rather than a record.
type WorkspacesAPIServer interface {
	// UploadSource stores a source tree and returns its reference. Bytes
	// do not travel in commands: a command's payload becomes an event in
	// the record's history, and a source tree would bury it.
	UploadSource(context.Context, *UploadSourceRequest) (*UploadSourceResponse, error)
	// DownloadSource hands back the workspace's current working tree.
	DownloadSource(*DownloadSourceRequest, grpc.ServerStreamingServer[DownloadSourceChunk]) error
	// ListRuntimes answers "which languages can I write a pipeline in
	// on THIS installation".
	ListRuntimes(context.Context, *ListRuntimesRequest) (*ListRuntimesResponse, error)
	// The working tree is EDITABLE: Studio reads and writes files
	// straight into the workspace, and every write is durable — that is
	// the whole point of the tree living on the server.
	ListFiles(context.Context, *ListFilesRequest) (*ListFilesResponse, error)
	ReadFile(context.Context, *ReadFileRequest) (*ReadFileResponse, error)
	WriteFile(context.Context, *WriteFileRequest) (*WriteFileResponse, error)
	DeleteFile(context.Context, *DeleteFileRequest) (*WriteFileResponse, error)
	mustEmbedUnimplementedWorkspacesAPIServer()
}

// UnimplementedWorkspacesAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkspacesAPIServer struct{}

func (UnimplementedWorkspacesAPIServer) UploadSource(context.Context, *UploadSourceRequest) (*UploadSourceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadSource not implemented")
}
func (UnimplementedWorkspacesAPIServer) DownloadSource(*DownloadSourceRequest, grpc.ServerStreamingServer[DownloadSourceChunk]) error {
	return status.Error(codes.Unimplemented, "method DownloadSource not implemented")
}
func (UnimplementedWorkspacesAPIServer) ListRuntimes(context.Context, *ListRuntimesRequest) (*ListRuntimesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRuntimes not implemented")
}
func (UnimplementedWorkspacesAPIServer) ListFiles(context.Context, *ListFilesRequest) (*ListFilesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFiles not implemented")
}
func (UnimplementedWorkspacesAPIServer) ReadFile(context.Context, *ReadFileRequest) (*ReadFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadFile not implemented")
}
func (UnimplementedWorkspacesAPIServer) WriteFile(context.Context, *WriteFileRequest) (*WriteFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WriteFile not implemented")
}
func (UnimplementedWorkspacesAPIServer) DeleteFile(context.Context, *DeleteFileRequest) (*WriteFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteFile not implemented")
}
func (UnimplementedWorkspacesAPIServer) mustEmbedUnimplementedWorkspacesAPIServer() {}
func (UnimplementedWorkspacesAPIServer) testEmbeddedByValue()                       {}

// UnsafeWorkspacesAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkspacesAPIServer will
// result in compilation errors.
type UnsafeWorkspacesAPIServer interface {
	mustEmbedUnimplementedWorkspacesAPIServer()
}

func RegisterWorkspacesAPIServer(s grpc.ServiceRegistrar, srv WorkspacesAPIServer) {
	// If the following call panics, it indicates UnimplementedWorkspacesAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkspacesAPI_ServiceDesc, srv)
}

func _WorkspacesAPI_UploadSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspacesAPIServer).UploadSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspacesAPI_UploadSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspacesAPIServer).UploadSource(ctx, req.(*UploadSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspacesAPI_DownloadSource_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownloadSourceRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WorkspacesAPIServer).DownloadSource(m, &grpc.GenericServerStream[DownloadSourceRequest, DownloadSourceChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkspacesAPI_DownloadSourceServer = grpc.ServerStreamingServer[DownloadSourceChunk]

func _WorkspacesAPI_ListRuntimes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRuntimesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspacesAPIServer).ListRuntimes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspacesAPI_ListRuntimes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspacesAPIServer).ListRuntimes(ctx, req.(*ListRuntimesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspacesAPI_ListFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspacesAPIServer).ListFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspacesAPI_ListFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspacesAPIServer).ListFiles(ctx, req.(*ListFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspacesAPI_ReadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspacesAPIServer).ReadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspacesAPI_ReadFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspacesAPIServer).ReadFile(ctx, req.(*ReadFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspacesAPI_WriteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspacesAPIServer).WriteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspacesAPI_WriteFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspacesAPIServer).WriteFile(ctx, req.(*WriteFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspacesAPI_DeleteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspacesAPIServer).DeleteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspacesAPI_DeleteFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspacesAPIServer).DeleteFile(ctx, req.(*DeleteFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkspacesAPI_ServiceDesc is the grpc.ServiceDesc for WorkspacesAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkspacesAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "graphene.management.v1.WorkspacesAPI",
	HandlerType: (*WorkspacesAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UploadSource",
			Handler:    _WorkspacesAPI_UploadSource_Handler,
		},
		{
			MethodName: "ListRuntimes",
			Handler:    _WorkspacesAPI_ListRuntimes_Handler,
		},
		{
			MethodName: "ListFiles",
			Handler:    _WorkspacesAPI_ListFiles_Handler,
		},
		{
			MethodName: "ReadFile",
			Handler:    _WorkspacesAPI_ReadFile_Handler,
		},
		{
			MethodName: "WriteFile",
			Handler:    _WorkspacesAPI_WriteFile_Handler,
		},
		{
			MethodName: "DeleteFile",
			Handler:    _WorkspacesAPI_DeleteFile_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DownloadSource",
			Handler:       _WorkspacesAPI_DownloadSource_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/management/v1/workspaces.proto",
}
